#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Bamboo
  module Engine
    class Parser < Racc::Parser

module_eval(<<'...end engine-parser.racc/module_eval...', 'engine-parser.racc', 199)
  # == Bamboo::Engine::Parser
  #
  # <tt>Bamboo::Engine::Parser</tt> provides a parser for Bamboo::Engine::Parser operating on a DOM-like data model provided by
  # Bamboo::Engine::Memory::Context and Bamboo::Engine::Memory::Node.
  #
  # The expression language is based on XQuery and XPath.
  #

  require 'bamboo/engine'
  require 'rational'
  require 'bigdecimal'
  require 'bigdecimal/util'

  # Within the context of a Bamboo::Engine::Memory::Context object, this will
  # parse the given string and return an object that can be run to return
  # an array if Bamboo::Engine::Memory::Node objects.
  #
  # Example:
  #
  #   parser  = Bamboo::Engine::Parser.new
  #   context = Bamboo::Engine::Memory::Context.new
  #   expr    = parser.parse('//foo', context)
  #   foos    = expr.run(context)
  #
  # Results in 'foos' being an array of all of the nodes in the
  # context that are named 'foo' regardless of their depth in the
  # node tree.
  def parse(text, context)
    @source = text
    @curpos = 0
    @context = context.merge
    @line = 0
    @col = 0

    @yydebug = true

    @last_token = nil

    do_parse
  end

  # Used internally by the parser to raise a Bamboo::Engine::ParserError
  # when the parse fails.
  def on_error(*args)
    raise Bamboo::Engine::ParserError.new("unable to parse '#{args[1]}' near line #{@line + 1}, column #{@col}")
  end


  @@regex = {
    :simple_tokens => %r{\.\.|::|!=|>=|<=|\/\/|\/>|:=|\.|@|[*]|\(|\)|\[|\]|\{|\}|\/|\||\+|-|=|>|<|&|,|;},
    :ncname => %r{(?:[a-zA-Z_][-a-zA-Z0-9_.]*)},
    :event_type => %r{(?:processing-instruction|comment|text|node)},
    :axis_name => %r{(?:attribute|child|child-or-self|descendant|descendant-or-self|method|self)},
    :namespace_name => %r{(?:context|global|local|session|universal)},
    :number => %r{(-?\d+(?:\.\d+)?|\.\d+)},
    :literal => %r{((?:"(?:[^\\"]*(?:\\.[^\\"]*)*)")|(?:'(?:[^\\']*(?:\\.[^\\']*)*)'))},
  }

  @@regex[:axis] = %r{(#{@@regex[:ncname]})\s*(?=::)}
  @@regex[:name_colon_star] = %r{(#{@@regex[:ncname]}:\*)}
  @@regex[:qname] = %r{((?:#{@@regex[:ncname]}:)?#{@@regex[:ncname]})}
  @@regex[:xmlns] = %r{((?:xmlns:)#{@@regex[:ncname]})}
  @@regex[:dollar_qname] = %r{\$#{@@regex[:qname]}}
  @@regex[:dollar_int] = %r{\$([0-9]+)}
  @@regex[:function_name] = %r{#{@@regex[:qname]}\??\*?\s*(?=\([^:])}

  @@ops = {
    '..' => :DOT_DOT,
    '::' => :COLON_COLON,
    '!=' => :NEQ,
    '>=' => :GTE,
    '<=' => :LTE,
    '//' => :SLASH_SLASH,
    '/>' => :SLASH_GT,
    ':=' => :COLON_EQUAL,
    '.'  => :DOT,
    '@'  => :AT,
    '*'  => :STAR,
    '('  => :LP,
    ')'  => :RP,
    '['  => :LB,
    ']'  => :RB,
    '{'  => :LC,
    '}'  => :RC,
    '/'  => :SLASH,
    '|'  => :PIPE,
    '+'  => :PLUS,
    '-'  => :MINUS,
    '='  => :EQ,
    '>'  => :GT,
    '<'  => :LT,
    '&'  => :AMP,
    ','  => :COMMA,
    ';'  => :SEMI
  }

  @@preceding_tokens = { }
  [%{
    @ :: ( 
    and or mod div 
    * 
    / // | + - = != < <= > >=
    == & && ||
  }.split(/\s*/), '[', ',', '$' ].each { |t| @@preceding_tokens[t] = true }

  @@regex[:general] = Regexp.compile(%{^(?:#{@@regex[:xmlns]}|#{@@regex[:function_name]}|#{@@regex[:axis]}|#{@@regex[:name_colon_star]}|#{@@regex[:qname]}|#{@@regex[:literal]}|#{@@regex[:number]}|#{@@regex[:dollar_qname]}|#{@@regex[:dollar_int]}|(#{@@regex[:simple_tokens]}))})

  def next_token  
    @token = nil
    white_space = 0
    new_line = 0
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end

    # skip comments delimited by (:  :)
    # comments can be nested
    # these are XPath 2.0 comments
    #
    if @curpos < @source.length && @source[@curpos..@curpos+1] == '(:'
      comment_depth = 1
      @curpos = @curpos + 2
      @col = @col + 2
      while comment_depth > 0 && @curpos < @source.length
        if @source[@curpos..@curpos+1] == '(:'
          comment_depth = comment_depth + 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        if @source[@curpos..@curpos+1] == ':)'
          comment_depth = comment_depth - 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        @curpos = @curpos + 1
        @col = @col + 1
      end
      white_space = white_space + 1
    end

    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end
        
    if @curpos >= @source.length
      @last_token = nil
      return [ false, false ]
    end

    #if new_line > 0 || white_space > 0
    #  @token = [ :SP, '' ]
    #end

    if @token.nil? && @last_token && ! @@preceding_tokens[@last_token[1]]
      if @source[@curpos..@curpos] == '*'
        @token = [ :STAR, '*' ]
      else
        if @source[@curpos..@source.length-1] =~ /^(#{@@regex[:ncname]})/
          ncname = $1
          case ncname
            when 'for'
              @token = [ :FOR, 'for' ]
            when 'return'
              @token = [ :RETURN, 'return' ]
            when 'in'
              @token = [ :IN, 'in' ]
            when 'let'
              @token = [ :LET, 'let' ]
            when 'except'
              @token = [ :EXCEPT, 'except' ]
            when 'every'
              @token = [ :EVERY, 'every' ]
            when 'some'
              @token = [ :SOME, 'some' ]
            when 'satisfies'
              @token = [ :SATISFIES, 'satisfies' ]
            when 'if'
              @token = [ :IF, 'if' ]
            when 'then'
              @token = [ :THEN, 'then' ]
            when 'else'
              @token = [ :ELSE, 'else' ]
            when 'to'
              @token = [ :TO, 'to' ]
            when 'and'
              @token = [ :AND, 'and' ]
            when 'or'
              @token = [ :OR, 'or' ]
            when 'mod'
              @token = [ :MOD, 'mod' ]
            when 'div'
              @token = [ :DIV, 'div' ]
            when 'err'
              @token = [ :ERR, 'err' ]
            #when '*doh*':
            #  # do nothing
            #  @token = nil
            else
              @token = nil
          end
        end
      end
    end
 
    if @token.nil? && @source[@curpos..@curpos+1] == '..'
      @token = [ :DOT_DOT, '..' ]
    end

    if @token.nil?
      if @curpos >= @source.length
        @token = [false, false]
        return @token
      end

      res = @@regex[:general].match(@source[@curpos..@source.length-1])
      #@source[@curpos..@source.length-1] =~ @@regex[:general]
      #res = [ nil, $1, $2, $3, $4, $5, $6, $7, $8 ]
      if res.nil?
        raise "Failed to parse '#{@source}' at #{@curpos}': #{@source[@curpos..@source.length-1]}"
      else
        if !res[1].nil?
          @token = [ :XMLNS_COLON_NCNAME, res[1] ]
        elsif !res[2].nil?
          if res[2] == 'if'
            @token = [ :IF, 'if' ]
          else
            if @source[@curpos+res[2].length .. @curpos+res[2].length + 1] =~ /^(\??\*?)/
              @token = [ :FUNCTION_NAME, res[2]+$1 ]
            else
              @token = [ :FUNCTION_NAME, res[2] ]
            end
          end
        elsif !res[3].nil?
          @token = [ res[3] == 'method' ? :AXIS_METHOD : :AXIS_NAME, res[3] ]
        elsif !res[4].nil?
          @token = [ :NAME_COLON_STAR, res[4] ]
        elsif !res[5].nil?
          qname = res[5]
          case qname
            when 'for'
              @token = [ :FOR, 'for' ]
            when 'return'
              @token = [ :RETURN, 'return' ]
            when 'in'
              @token = [ :IN, 'in' ]
            when 'let'
              @token = [ :LET, 'let' ]
            when 'except'
              @token = [ :EXCEPT, 'except' ]
            when 'every'
              @token = [ :EVERY, 'every' ]
            when 'some'
              @token = [ :SOME, 'some' ]   
            when 'satisfies'
              @token = [ :SATISFIES, 'satisfies' ]
            when 'if'
              @token = [ :IF, 'if' ]
            when 'then'
              @token = [ :THEN, 'then' ]
            when 'else'
              @token = [ :ELSE, 'else' ]
            when 'with'
              @token = [ :WITH, 'with' ]
            when 'err'
              @token = [ :ERR, 'err' ]
            else
              @token = [ :QNAME, qname ]
          end
        elsif !res[6].nil?
          s = res[6]
          @curpos = @curpos + s.length
          @col = @col + s.length
          s = s[1..s.length-2]
          s.gsub!(/\\n/, "\n")
          s.gsub!(/\\'/, "'")
          s.gsub!(/\\"/, '"')
          @line += s.split(/\n/).count
          @curpos = @curpos - s.length
          @col = @col - s.length
          @token = [ :LITERAL, s ]
        elsif !res[7].nil?
          @token = [ :NUMBER, res[7] ]
        elsif !res[8].nil?
          @curpos = @curpos + 1
          @col = @col + 1
          @token = [ :DOLLAR_QNAME, res[8] ]
        elsif !res[9].nil?
          @curpos = @curpos + 1
          @col = @col + 1
          @token = [ :DOLLAR_QNAME, res[9] ]
        elsif !res[10].nil?
          @token = [ @@ops[res[10]] || res[10], res[10] ]
        else
          raise "Failed to parse '#{@source}' at #{@curpos}: #{@source[@curpos..@source.length-1]}"
        end
      end
    end

    if !@token[1].nil?
      @curpos = @curpos + @token[1].length
      @col = @col + @token[1].length
    end
    @last_token = @token
    return @token
  end
...end engine-parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    64,    65,    37,    39,   177,    47,     5,     7,    64,    65,
   137,    29,   108,    90,    42,   137,    51,   137,    74,    75,
    76,    77,    28,    85,    35,   149,   173,   178,     3,   138,
   152,    17,    20,   176,   170,   136,    40,    44,    48,     2,
     8,    84,    15,    21,    26,    92,    34,    37,    39,   140,
    47,     5,     7,   105,     3,   106,    29,    72,    20,    42,
   121,    51,   102,   103,    48,     2,     8,    28,    54,    35,
    26,    90,    34,     3,   142,   143,    17,    20,    67,    68,
    69,    40,    44,    48,     2,     8,    66,    15,    21,    26,
    39,    34,    47,     5,     7,   -20,     3,    90,    29,    90,
    20,    42,   158,    51,    64,    65,    48,     2,     8,    28,
    54,    35,    26,   157,    34,     3,   183,   -19,    17,    20,
    67,    68,    69,    40,    44,    48,     2,     8,   108,    15,
    21,    26,    39,    34,    47,   153,     7,    78,    79,   110,
   -19,    80,    81,    82,    83,    74,    75,    76,    77,    64,
    65,    28,   121,    35,    64,    65,   139,     3,    60,   109,
    17,    20,    64,    65,   155,    40,    44,    48,     2,     8,
   141,    15,    21,    26,    39,    34,    47,   146,     7,    56,
     3,    67,    68,    69,    20,    64,    65,    64,    65,   145,
    48,     2,     8,    28,    54,    35,    26,   nil,    34,     3,
   102,   103,    17,    20,    64,    65,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,     5,
     7,   nil,     3,   nil,    29,   nil,    20,    42,   nil,    51,
    64,    65,    48,     2,     8,    28,    54,    35,    26,   nil,
    34,     3,   102,   103,    17,    20,    64,    65,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,   nil,     7,   nil,     3,    64,    65,   nil,    20,    76,
    77,    76,    77,   nil,    48,     2,     8,    28,    54,    35,
    26,   nil,    34,     3,    39,   nil,    47,    20,     7,   nil,
    20,    40,    44,    48,     2,     8,    20,    15,    21,    26,
    54,    34,    26,    28,    34,    35,    54,   nil,    26,     3,
    34,   nil,    17,    20,   102,   103,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,   nil,
     7,   nil,     3,    64,    65,   nil,    20,    76,    77,    76,
    77,   nil,    48,     2,     8,    28,    54,    35,    26,   nil,
    34,     3,    76,    77,    17,    20,    76,    77,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,   nil,     7,   nil,     3,    76,    77,   nil,    20,    76,
    77,    64,    65,   nil,    48,     2,     8,    28,    54,    35,
    26,   nil,    34,     3,    98,    99,    17,    20,    64,    65,
   nil,    40,    44,    48,     2,     8,   nil,    15,    21,    26,
    39,    34,    47,     5,     7,   nil,     3,   nil,    29,   nil,
    20,    42,   nil,    51,   102,   103,    48,     2,     8,    28,
    54,    35,    26,   nil,    34,     3,   102,   103,    17,    20,
    98,    99,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,    39,    34,    47,    20,     7,    94,    95,    62,
    63,    64,    65,   102,   103,    54,   nil,    26,   nil,    34,
   nil,    28,   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,
   nil,    20,   nil,   nil,   nil,    40,    44,    48,     2,     8,
   nil,    15,    21,    26,    39,    34,    47,     5,     7,   nil,
   nil,   nil,    29,   nil,   nil,    42,   nil,    51,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,   nil,     3,
   nil,   nil,    17,    20,   nil,   nil,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,     5,
     7,   nil,   nil,   nil,    29,   nil,   nil,    42,   nil,    51,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,
   nil,     3,   nil,   nil,    17,    20,   nil,   nil,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,     5,     7,   nil,   nil,   nil,    29,   nil,   nil,    42,
   nil,    51,   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,
   nil,   nil,   nil,     3,   nil,   nil,    17,    20,   nil,   nil,
   nil,    40,    44,    48,     2,     8,   nil,    15,    21,    26,
    39,    34,    47,     5,     7,   nil,   nil,   nil,    29,   nil,
   nil,    42,   nil,    51,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,    17,    20,
   nil,   nil,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,    39,    34,    47,     5,     7,   nil,   nil,   nil,
    29,   nil,   nil,    42,   nil,    51,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,
    17,    20,   nil,   nil,   nil,    40,    44,    48,     2,     8,
   nil,    15,    21,    26,    39,    34,    47,   nil,     7,    78,
    79,   nil,   nil,    80,    81,    82,    83,    74,    75,    76,
    77,   nil,   nil,    28,   nil,    35,   nil,   nil,   nil,     3,
   nil,   nil,    17,    20,   nil,   nil,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,   nil,
     7,    78,    79,   nil,   nil,    80,    81,    82,    83,   nil,
   nil,    76,    77,   nil,   nil,    28,   nil,    35,   nil,   nil,
   nil,     3,   nil,   nil,    17,    20,   nil,   nil,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,   nil,     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,
   nil,   nil,   nil,     3,   nil,   nil,    17,    20,   nil,   nil,
   nil,    40,    44,    48,     2,     8,   nil,    15,    21,    26,
    39,    34,    47,     5,     7,   nil,   nil,   nil,    29,   nil,
   nil,    42,   nil,    51,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,    17,    20,
   nil,   nil,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,    39,    34,    47,   nil,     7,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,
    17,    20,   nil,   nil,   nil,    40,    44,    48,     2,     8,
   nil,    15,    21,    26,    39,    34,    47,     5,     7,   nil,
   nil,   nil,    29,   nil,   nil,    42,   nil,    51,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,   nil,     3,
   nil,   nil,    17,    20,   nil,   nil,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,     5,
     7,   nil,   nil,   nil,    29,   nil,   nil,    42,   nil,    51,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,
   nil,     3,   nil,   nil,    17,    20,   nil,   nil,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,     5,     7,   nil,   nil,   nil,    29,   nil,   nil,    42,
   nil,    51,   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,
   nil,   nil,   nil,     3,   nil,   nil,    17,    20,   nil,   nil,
   nil,    40,    44,    48,     2,     8,   nil,    15,    21,    26,
    39,    34,    47,     5,     7,   nil,   nil,   nil,    29,   nil,
   nil,    42,   nil,    51,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,    17,    20,
   nil,   nil,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,    39,    34,    47,     5,     7,   nil,   nil,   nil,
    29,   nil,   nil,    42,   nil,    51,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,
    17,    20,   nil,   nil,   nil,    40,    44,    48,     2,     8,
   nil,    15,    21,    26,    39,    34,    47,   nil,     7,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,   nil,     3,
   nil,   nil,    17,    20,   nil,   nil,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,   nil,
     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,
   nil,     3,   nil,   nil,    17,    20,   nil,   nil,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,   nil,     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,
   nil,   nil,   nil,     3,   nil,   nil,    17,    20,   nil,   nil,
   nil,    40,    44,    48,     2,     8,   nil,    15,    21,    26,
    39,    34,    47,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,    17,    20,
   nil,   nil,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,    39,    34,    47,     5,     7,   nil,   nil,   nil,
    29,   nil,   nil,    42,   nil,    51,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,
    17,    20,   nil,   nil,   nil,    40,    44,    48,     2,     8,
   nil,    15,    21,    26,    39,    34,    47,   nil,     7,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,   nil,     3,
    39,   nil,    47,    20,     7,   nil,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,   nil,    34,   nil,    28,
   nil,    35,   nil,   nil,   nil,     3,    39,   nil,    47,    20,
     7,   nil,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,   nil,    34,   nil,    28,   nil,    35,   nil,   nil,
   nil,     3,   nil,   nil,    17,    20,   nil,   nil,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,    39,    34,
    47,   nil,     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,
   nil,   nil,   nil,     3,   nil,   nil,    17,    20,   nil,   nil,
   nil,    40,    44,    48,     2,     8,   nil,    15,    21,    26,
    39,    34,    47,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,    17,    20,
   nil,   nil,   nil,    40,    44,    48,     2,     8,   nil,    15,
    21,    26,    39,    34,    47,   nil,     7,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    35,   nil,   nil,   nil,     3,   nil,   nil,
    17,    20,   nil,   nil,   nil,    40,    44,    48,     2,     8,
   nil,    15,    21,    26,    39,    34,    47,     5,     7,   nil,
   nil,   nil,    29,   nil,   nil,    42,   nil,    51,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,   nil,     3,
   nil,   nil,    17,    20,   nil,   nil,   nil,    40,    44,    48,
     2,     8,   nil,    15,    21,    26,    39,    34,    47,   nil,
     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    35,   nil,   nil,
   nil,     3,   nil,   nil,    17,    20,   nil,   nil,   nil,    40,
    44,    48,     2,     8,   nil,    15,    21,    26,   nil,    34 ]

racc_action_check = [
    91,    91,     0,     0,   162,     0,     0,     0,   159,   159,
   100,     0,    86,    29,     0,   104,     0,    88,   181,   181,
   181,   181,     0,    27,     0,   100,   155,   162,     0,    88,
   104,     0,     0,   159,   146,    86,     0,     0,     0,     0,
     0,    25,     0,     0,     0,    35,     0,   106,   106,    91,
   106,   106,   106,    53,   142,    53,   106,    21,   142,   106,
    93,   106,   167,   167,   142,   142,   142,   106,   142,   106,
   142,    42,   142,   106,    93,    93,   106,   106,   125,   125,
   125,   106,   106,   106,   106,   106,    12,   106,   106,   106,
    56,   106,    56,    56,    56,   163,    44,   137,    56,    51,
    44,    56,   116,    56,   179,   179,    44,    44,    44,    56,
    44,    56,    44,   114,    44,    56,   179,   161,    56,    56,
   126,   126,   126,    56,    56,    56,    56,    56,    57,    56,
    56,    56,   177,    56,   177,   105,   177,   161,   161,    59,
   161,   161,   161,   161,   161,   161,   161,   161,   161,    58,
    58,   177,    70,   177,   107,   107,    90,   177,     8,    58,
   177,   177,   169,   169,   107,   177,   177,   177,   177,   177,
    92,   177,   177,   177,    98,   177,    98,    95,    98,     5,
    40,    13,    13,    13,    40,   172,   172,    10,    10,    94,
    40,    40,    40,    98,    40,    98,    40,   nil,    40,    98,
   111,   111,    98,    98,   156,   156,   nil,    98,    98,    98,
    98,    98,   nil,    98,    98,    98,   173,    98,   173,   173,
   173,   nil,   143,   nil,   173,   nil,   143,   173,   nil,   173,
   113,   113,   143,   143,   143,   173,   143,   173,   143,   nil,
   143,   173,   168,   168,   173,   173,   171,   171,   nil,   173,
   173,   173,   173,   173,   nil,   173,   173,   173,    85,   173,
    85,   nil,    85,   nil,    62,   166,   166,   nil,    62,   123,
   123,   124,   124,   nil,    62,    62,    62,    85,    62,    85,
    62,   nil,    62,    85,    84,   nil,    84,    85,    84,   nil,
     2,    85,    85,    85,    85,    85,    96,    85,    85,    85,
     2,    85,     2,    84,     2,    84,    96,   nil,    96,    84,
    96,   nil,    84,    84,   101,   101,   nil,    84,    84,    84,
    84,    84,   nil,    84,    84,    84,    17,    84,    17,   nil,
    17,   nil,    63,    87,    87,   nil,    63,   127,   127,   128,
   128,   nil,    63,    63,    63,    17,    63,    17,    63,   nil,
    63,    17,   129,   129,    17,    17,   130,   130,   nil,    17,
    17,    17,    17,    17,   nil,    17,    17,    17,    83,    17,
    83,   nil,    83,   nil,   102,   131,   131,   nil,   102,   132,
   132,   175,   175,   nil,   102,   102,   102,    83,   102,    83,
   102,   nil,   102,    83,   134,   134,    83,    83,   165,   165,
   nil,    83,    83,    83,    83,    83,   nil,    83,    83,    83,
   158,    83,   158,   158,   158,   nil,   103,   nil,   158,   nil,
   103,   158,   nil,   158,    49,    49,   103,   103,   103,   158,
   103,   158,   103,   nil,   103,   158,    97,    97,   158,   158,
    41,    41,   nil,   158,   158,   158,   158,   158,   nil,   158,
   158,   158,   157,   158,   157,     9,   157,    37,    37,     9,
     9,   184,   184,   112,   112,     9,   nil,     9,   nil,     9,
   nil,   157,   nil,   157,   nil,   nil,   nil,   157,   nil,   nil,
   nil,   157,   nil,   nil,   nil,   157,   157,   157,   157,   157,
   nil,   157,   157,   157,   152,   157,   152,   152,   152,   nil,
   nil,   nil,   152,   nil,   nil,   152,   nil,   152,   nil,   nil,
   nil,   nil,   nil,   152,   nil,   152,   nil,   nil,   nil,   152,
   nil,   nil,   152,   152,   nil,   nil,   nil,   152,   152,   152,
   152,   152,   nil,   152,   152,   152,    28,   152,    28,    28,
    28,   nil,   nil,   nil,    28,   nil,   nil,    28,   nil,    28,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    28,   nil,   nil,
   nil,    28,   nil,   nil,    28,    28,   nil,   nil,   nil,    28,
    28,    28,    28,    28,   nil,    28,    28,    28,   149,    28,
   149,   149,   149,   nil,   nil,   nil,   149,   nil,   nil,   149,
   nil,   149,   nil,   nil,   nil,   nil,   nil,   149,   nil,   149,
   nil,   nil,   nil,   149,   nil,   nil,   149,   149,   nil,   nil,
   nil,   149,   149,   149,   149,   149,   nil,   149,   149,   149,
    34,   149,    34,    34,    34,   nil,   nil,   nil,    34,   nil,
   nil,    34,   nil,    34,   nil,   nil,   nil,   nil,   nil,    34,
   nil,    34,   nil,   nil,   nil,    34,   nil,   nil,    34,    34,
   nil,   nil,   nil,    34,    34,    34,    34,    34,   nil,    34,
    34,    34,   145,    34,   145,   145,   145,   nil,   nil,   nil,
   145,   nil,   nil,   145,   nil,   145,   nil,   nil,   nil,   nil,
   nil,   145,   nil,   145,   nil,   nil,   nil,   145,   nil,   nil,
   145,   145,   nil,   nil,   nil,   145,   145,   145,   145,   145,
   nil,   145,   145,   145,    82,   145,    82,   nil,    82,    24,
    24,   nil,   nil,    24,    24,    24,    24,    24,    24,    24,
    24,   nil,   nil,    82,   nil,    82,   nil,   nil,   nil,    82,
   nil,   nil,    82,    82,   nil,   nil,   nil,    82,    82,    82,
    82,    82,   nil,    82,    82,    82,    81,    82,    81,   nil,
    81,   133,   133,   nil,   nil,   133,   133,   133,   133,   nil,
   nil,   133,   133,   nil,   nil,    81,   nil,    81,   nil,   nil,
   nil,    81,   nil,   nil,    81,    81,   nil,   nil,   nil,    81,
    81,    81,    81,    81,   nil,    81,    81,    81,    80,    81,
    80,   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    80,   nil,    80,
   nil,   nil,   nil,    80,   nil,   nil,    80,    80,   nil,   nil,
   nil,    80,    80,    80,    80,    80,   nil,    80,    80,    80,
   139,    80,   139,   139,   139,   nil,   nil,   nil,   139,   nil,
   nil,   139,   nil,   139,   nil,   nil,   nil,   nil,   nil,   139,
   nil,   139,   nil,   nil,   nil,   139,   nil,   nil,   139,   139,
   nil,   nil,   nil,   139,   139,   139,   139,   139,   nil,   139,
   139,   139,    79,   139,    79,   nil,    79,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    79,   nil,    79,   nil,   nil,   nil,    79,   nil,   nil,
    79,    79,   nil,   nil,   nil,    79,    79,    79,    79,    79,
   nil,    79,    79,    79,   138,    79,   138,   138,   138,   nil,
   nil,   nil,   138,   nil,   nil,   138,   nil,   138,   nil,   nil,
   nil,   nil,   nil,   138,   nil,   138,   nil,   nil,   nil,   138,
   nil,   nil,   138,   138,   nil,   nil,   nil,   138,   138,   138,
   138,   138,   nil,   138,   138,   138,   121,   138,   121,   121,
   121,   nil,   nil,   nil,   121,   nil,   nil,   121,   nil,   121,
   nil,   nil,   nil,   nil,   nil,   121,   nil,   121,   nil,   nil,
   nil,   121,   nil,   nil,   121,   121,   nil,   nil,   nil,   121,
   121,   121,   121,   121,   nil,   121,   121,   121,   108,   121,
   108,   108,   108,   nil,   nil,   nil,   108,   nil,   nil,   108,
   nil,   108,   nil,   nil,   nil,   nil,   nil,   108,   nil,   108,
   nil,   nil,   nil,   108,   nil,   nil,   108,   108,   nil,   nil,
   nil,   108,   108,   108,   108,   108,   nil,   108,   108,   108,
     7,   108,     7,     7,     7,   nil,   nil,   nil,     7,   nil,
   nil,     7,   nil,     7,   nil,   nil,   nil,   nil,   nil,     7,
   nil,     7,   nil,   nil,   nil,     7,   nil,   nil,     7,     7,
   nil,   nil,   nil,     7,     7,     7,     7,     7,   nil,     7,
     7,     7,   183,     7,   183,   183,   183,   nil,   nil,   nil,
   183,   nil,   nil,   183,   nil,   183,   nil,   nil,   nil,   nil,
   nil,   183,   nil,   183,   nil,   nil,   nil,   183,   nil,   nil,
   183,   183,   nil,   nil,   nil,   183,   183,   183,   183,   183,
   nil,   183,   183,   183,    74,   183,    74,   nil,    74,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    74,   nil,    74,   nil,   nil,   nil,    74,
   nil,   nil,    74,    74,   nil,   nil,   nil,    74,    74,    74,
    74,    74,   nil,    74,    74,    74,    78,    74,    78,   nil,
    78,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    78,   nil,    78,   nil,   nil,
   nil,    78,   nil,   nil,    78,    78,   nil,   nil,   nil,    78,
    78,    78,    78,    78,   nil,    78,    78,    78,    77,    78,
    77,   nil,    77,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    77,   nil,    77,
   nil,   nil,   nil,    77,   nil,   nil,    77,    77,   nil,   nil,
   nil,    77,    77,    77,    77,    77,   nil,    77,    77,    77,
    76,    77,    76,   nil,    76,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    76,
   nil,    76,   nil,   nil,   nil,    76,   nil,   nil,    76,    76,
   nil,   nil,   nil,    76,    76,    76,    76,    76,   nil,    76,
    76,    76,    64,    76,    64,    64,    64,   nil,   nil,   nil,
    64,   nil,   nil,    64,   nil,    64,   nil,   nil,   nil,   nil,
   nil,    64,   nil,    64,   nil,   nil,   nil,    64,   nil,   nil,
    64,    64,   nil,   nil,   nil,    64,    64,    64,    64,    64,
   nil,    64,    64,    64,    65,    64,    65,   nil,    65,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    65,   nil,    65,   nil,   nil,   nil,    65,
    66,   nil,    66,    65,    66,   nil,   nil,    65,    65,    65,
    65,    65,   nil,    65,    65,    65,   nil,    65,   nil,    66,
   nil,    66,   nil,   nil,   nil,    66,    67,   nil,    67,    66,
    67,   nil,   nil,    66,    66,    66,    66,    66,   nil,    66,
    66,    66,   nil,    66,   nil,    67,   nil,    67,   nil,   nil,
   nil,    67,   nil,   nil,    67,    67,   nil,   nil,   nil,    67,
    67,    67,    67,    67,   nil,    67,    67,    67,    68,    67,
    68,   nil,    68,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    68,
   nil,   nil,   nil,    68,   nil,   nil,    68,    68,   nil,   nil,
   nil,    68,    68,    68,    68,    68,   nil,    68,    68,    68,
    69,    68,    69,   nil,    69,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    69,
   nil,    69,   nil,   nil,   nil,    69,   nil,   nil,    69,    69,
   nil,   nil,   nil,    69,    69,    69,    69,    69,   nil,    69,
    69,    69,    75,    69,    75,   nil,    75,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    75,   nil,    75,   nil,   nil,   nil,    75,   nil,   nil,
    75,    75,   nil,   nil,   nil,    75,    75,    75,    75,    75,
   nil,    75,    75,    75,    72,    75,    72,    72,    72,   nil,
   nil,   nil,    72,   nil,   nil,    72,   nil,    72,   nil,   nil,
   nil,   nil,   nil,    72,   nil,    72,   nil,   nil,   nil,    72,
   nil,   nil,    72,    72,   nil,   nil,   nil,    72,    72,    72,
    72,    72,   nil,    72,    72,    72,    99,    72,    99,   nil,
    99,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    99,   nil,    99,   nil,   nil,
   nil,    99,   nil,   nil,    99,    99,   nil,   nil,   nil,    99,
    99,    99,    99,    99,   nil,    99,    99,    99,   nil,    99 ]

racc_action_pointer = [
    -5,   nil,   253,   nil,   nil,   167,   nil,  1032,   112,   418,
   184,   nil,    46,   144,   nil,   nil,   nil,   318,   nil,   nil,
   nil,    45,   nil,   nil,   684,    19,   nil,   -17,   528,     5,
   nil,   nil,   nil,   nil,   612,    -4,   nil,   449,   nil,   nil,
   147,   417,    63,   nil,    63,   nil,   nil,   nil,   nil,   383,
   nil,    91,   nil,    53,   nil,   nil,    82,   123,   146,   126,
   nil,   nil,   231,   299,  1284,  1326,  1352,  1378,  1420,  1462,
   125,   nil,  1546,   nil,  1116,  1504,  1242,  1200,  1158,   864,
   780,   738,   696,   360,   276,   250,     7,   330,    12,   nil,
   138,    -3,   120,    33,   183,   171,   259,   395,   166,  1588,
     5,   273,   341,   383,    10,   135,    40,   151,   990,   nil,
   nil,   159,   422,   227,   108,   nil,    96,   nil,   nil,   nil,
   nil,   948,   nil,   234,   236,    41,    83,   302,   304,   317,
   321,   340,   344,   726,   371,   nil,   nil,    89,   906,   822,
   nil,   nil,    21,   189,   nil,   654,    24,   nil,   nil,   570,
   nil,   nil,   486,   nil,   nil,    12,   201,   444,   402,     5,
   nil,   112,    -1,    90,   nil,   395,   262,    21,   201,   159,
   nil,   243,   182,   208,   nil,   378,   nil,   124,   nil,   101,
   nil,   -15,   nil,  1074,   458 ]

racc_action_default = [
    -3,   -91,  -106,   -79,   -68,  -106,    -1,   -98,  -106,  -106,
    -4,   -74,   -58,   -49,    -5,   -93,   -84,  -106,   -52,    -6,
  -105,   -94,   -80,   -56,   -42,    -7,  -102,   -59,  -106,  -106,
    -8,   -90,   -62,    -9,  -106,  -106,   -84,  -106,   -10,   -88,
   -69,   -33,  -106,   -11,  -106,   -35,   -12,   -92,   -78,   -67,
   -38,  -106,   -13,  -106,  -103,   -82,  -106,   -99,  -100,  -106,
   -83,   -81,  -106,  -106,  -106,  -106,  -106,  -106,  -106,  -106,
   -77,   -57,   -98,   -96,  -106,  -106,  -106,  -106,  -106,  -106,
  -106,  -106,  -106,  -106,  -106,  -106,  -106,  -100,  -106,   -28,
  -106,  -106,  -106,   -64,  -106,  -106,  -106,   -70,  -106,  -106,
  -106,   -71,  -106,  -106,  -106,  -106,    -3,  -106,  -106,   -89,
   -97,   -72,   -73,   -14,   -15,   -16,  -106,   -60,   -53,   -54,
   -55,  -106,   -85,   -47,   -48,   -50,   -51,   -39,   -40,   -43,
   -44,   -45,   -46,   -42,   -34,   -61,   -41,  -106,  -106,  -106,
  -104,   -95,  -106,  -106,   -63,  -106,  -106,   -36,   -37,  -106,
   -75,   -76,  -106,   185,    -2,  -106,  -101,  -106,  -106,  -106,
   -21,   -42,  -106,    -8,   -29,   -27,   -30,   -65,   -66,   -23,
   -24,   -31,   -32,  -106,   -17,   -18,   -86,  -106,   -87,   -26,
   -22,   -19,   -20,  -106,   -25 ]

racc_goto_table = [
    58,     6,    97,    55,   115,   160,   101,    96,   123,   124,
    61,    96,   127,   128,   129,   130,   131,   132,   133,   163,
    70,    87,    71,    88,   111,   112,   134,    91,    86,    96,
    96,   144,   133,   133,   116,   117,   100,   150,   151,   164,
    93,   147,   148,   125,   126,   104,   162,   114,    53,   107,
    73,   nil,   nil,   nil,   135,   161,   nil,   113,   nil,   nil,
   nil,   180,   nil,   nil,   nil,    87,   nil,   nil,   nil,    96,
    96,   nil,   118,   119,   120,   182,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   174,    61,   nil,   nil,
   nil,   156,   nil,   nil,   167,   168,   nil,   154,   nil,    96,
    96,   181,   nil,   nil,   159,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   116,   nil,   nil,   nil,
   nil,   165,   166,   nil,   nil,   nil,   nil,   nil,   169,   nil,
   nil,   nil,   171,   nil,   nil,   172,   nil,   nil,   nil,   nil,
   nil,   175,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   179,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   184 ]

racc_goto_check = [
     3,     2,    34,    39,    14,    16,    34,    36,    17,    17,
    39,    36,    17,    17,    17,    17,    17,    17,    17,     7,
    32,     3,    27,    19,    34,    34,    21,     3,    25,    36,
    36,    33,    17,    17,    15,    15,    19,    37,    37,    20,
    32,    22,    22,    26,    26,    19,    18,    13,     1,     3,
    41,   nil,   nil,   nil,    15,    17,   nil,     3,   nil,   nil,
   nil,    16,   nil,   nil,   nil,     3,   nil,   nil,   nil,    36,
    36,   nil,    27,    27,    27,     7,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    14,    39,   nil,   nil,
   nil,     3,   nil,   nil,    34,    34,   nil,     2,   nil,    36,
    36,    17,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    15,   nil,   nil,   nil,
   nil,     3,     3,   nil,   nil,   nil,   nil,   nil,     3,   nil,
   nil,   nil,     3,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    48,     1,    -7,   nil,   nil,   nil,  -102,   nil,   nil,
   nil,   nil,   nil,   -18,   -61,   -31,  -116,   -66,   -75,    -6,
   -98,   -58,   -57,   nil,   nil,     0,   -33,     5,   nil,   nil,
   nil,   nil,     4,   -62,   -38,   nil,   -33,   -65,   nil,     1,
   nil,    29,   nil ]

racc_goto_default = [
   nil,   nil,   nil,    10,    14,    19,    25,    30,    33,    38,
    43,    46,    52,   nil,   nil,    12,   nil,    24,   nil,   nil,
    89,    41,    45,    50,     1,    57,    13,    18,    23,    27,
    32,    36,   nil,   nil,    49,     4,     9,    11,    16,    22,
   122,    31,    59 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 54, :_reduce_1,
  3, 54, :_reduce_2,
  0, 55, :_reduce_none,
  1, 55, :_reduce_none,
  1, 55, :_reduce_none,
  1, 55, :_reduce_6,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  3, 65, :_reduce_14,
  3, 64, :_reduce_15,
  1, 66, :_reduce_16,
  3, 66, :_reduce_17,
  3, 67, :_reduce_18,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  1, 71, :_reduce_21,
  3, 71, :_reduce_22,
  4, 57, :_reduce_23,
  4, 58, :_reduce_24,
  8, 61, :_reduce_25,
  6, 61, :_reduce_26,
  4, 62, :_reduce_27,
  1, 72, :_reduce_28,
  3, 72, :_reduce_29,
  3, 73, :_reduce_30,
  4, 63, :_reduce_31,
  4, 63, :_reduce_32,
  1, 59, :_reduce_none,
  3, 59, :_reduce_34,
  1, 74, :_reduce_none,
  3, 74, :_reduce_36,
  3, 74, :_reduce_37,
  1, 75, :_reduce_none,
  3, 75, :_reduce_39,
  3, 75, :_reduce_40,
  3, 77, :_reduce_41,
  1, 76, :_reduce_none,
  3, 76, :_reduce_43,
  3, 76, :_reduce_44,
  3, 76, :_reduce_45,
  3, 76, :_reduce_46,
  3, 60, :_reduce_47,
  3, 60, :_reduce_48,
  1, 70, :_reduce_none,
  3, 70, :_reduce_50,
  3, 70, :_reduce_51,
  1, 79, :_reduce_none,
  3, 79, :_reduce_53,
  3, 79, :_reduce_54,
  3, 79, :_reduce_55,
  1, 80, :_reduce_none,
  2, 80, :_reduce_57,
  1, 81, :_reduce_none,
  1, 81, :_reduce_59,
  3, 82, :_reduce_60,
  3, 82, :_reduce_61,
  1, 68, :_reduce_62,
  3, 68, :_reduce_63,
  0, 86, :_reduce_none,
  2, 86, :_reduce_65,
  2, 86, :_reduce_66,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 88, :_reduce_69,
  2, 88, :_reduce_70,
  2, 88, :_reduce_71,
  3, 88, :_reduce_72,
  3, 88, :_reduce_73,
  1, 87, :_reduce_74,
  3, 87, :_reduce_75,
  3, 87, :_reduce_76,
  2, 90, :_reduce_77,
  1, 90, :_reduce_78,
  1, 90, :_reduce_79,
  1, 91, :_reduce_80,
  2, 91, :_reduce_81,
  2, 91, :_reduce_82,
  2, 89, :_reduce_83,
  0, 85, :_reduce_84,
  2, 85, :_reduce_85,
  3, 93, :_reduce_86,
  3, 93, :_reduce_87,
  1, 84, :_reduce_88,
  3, 84, :_reduce_89,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  1, 84, :_reduce_92,
  1, 84, :_reduce_93,
  1, 84, :_reduce_none,
  3, 84, :_reduce_95,
  2, 84, :_reduce_96,
  3, 94, :_reduce_97,
  0, 95, :_reduce_98,
  1, 95, :_reduce_none,
  1, 78, :_reduce_100,
  3, 78, :_reduce_101,
  1, 92, :_reduce_none,
  1, 92, :_reduce_103,
  3, 92, :_reduce_104,
  1, 92, :_reduce_none ]

racc_reduce_n = 106

racc_shift_n = 185

racc_token_table = {
  false => 0,
  :error => 1,
  :SEMI => 2,
  :ERR => 3,
  :WITH => 4,
  :COMMA => 5,
  :COLON_EQUAL => 6,
  :LET => 7,
  :DOLLAR_QNAME => 8,
  :XMLNS_COLON_NCNAME => 9,
  :LITERAL => 10,
  :IF => 11,
  :LP => 12,
  :RP => 13,
  :THEN => 14,
  :ELSE => 15,
  :FOR => 16,
  :RETURN => 17,
  :IN => 18,
  :SOME => 19,
  :SATISFIES => 20,
  :EVERY => 21,
  :OR => 22,
  :AND => 23,
  :EXCEPT => 24,
  :EQ => 25,
  :NEQ => 26,
  :LB => 27,
  :RB => 28,
  :LT => 29,
  :GT => 30,
  :LTE => 31,
  :GTE => 32,
  :DOT_DOT => 33,
  :TO => 34,
  :PLUS => 35,
  :MINUS => 36,
  :STAR => 37,
  :DIV => 38,
  :MOD => 39,
  :PIPE => 40,
  :SLASH => 41,
  :SLASH_SLASH => 42,
  :DOT => 43,
  :AT => 44,
  :AXIS_NAME => 45,
  :COLON_COLON => 46,
  :NUMBER => 47,
  :FUNCTION_NAME => 48,
  :QNAME => 49,
  :SLASH_GT => 50,
  :LC => 51,
  :RC => 52 }

racc_nt_base = 53

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SEMI",
  "ERR",
  "WITH",
  "COMMA",
  "COLON_EQUAL",
  "LET",
  "DOLLAR_QNAME",
  "XMLNS_COLON_NCNAME",
  "LITERAL",
  "IF",
  "LP",
  "RP",
  "THEN",
  "ELSE",
  "FOR",
  "RETURN",
  "IN",
  "SOME",
  "SATISFIES",
  "EVERY",
  "OR",
  "AND",
  "EXCEPT",
  "EQ",
  "NEQ",
  "LB",
  "RB",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "DOT_DOT",
  "TO",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "MOD",
  "PIPE",
  "SLASH",
  "SLASH_SLASH",
  "DOT",
  "AT",
  "AXIS_NAME",
  "COLON_COLON",
  "NUMBER",
  "FUNCTION_NAME",
  "QNAME",
  "SLASH_GT",
  "LC",
  "RC",
  "$start",
  "statements",
  "statement",
  "expr",
  "let_expr",
  "ns_expr",
  "or_expr",
  "range_expr",
  "if_expr",
  "for_expr",
  "quant_expr",
  "with_expr",
  "err_expr",
  "expr_set_list",
  "expr_set",
  "path_expr",
  "num_expr",
  "additive_expr",
  "num_list",
  "for_vars",
  "for_var",
  "and_expr",
  "equality_expr",
  "relational_expr",
  "tuple",
  "args",
  "multiplicative_expr",
  "unary_expr",
  "union_expr",
  "union_expr_x",
  "location_path",
  "primary_expr",
  "predicates",
  "segment",
  "relative_location_path",
  "absolute_location_path",
  "axis_name",
  "step",
  "axis",
  "node_test",
  "predicate",
  "list",
  "opt_args" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 12)
  def _reduce_1(val, _values, result)
     result = Bamboo::Engine::Parser::StatementList.new; result.add_statement(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 13)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_statement(val[2]) 
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 18)
  def _reduce_6(val, _values, result)
     result = nil 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 28)
  def _reduce_14(val, _values, result)
     result = Bamboo::Engine::Parser::ErrExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 30)
  def _reduce_15(val, _values, result)
     result = Bamboo::Engine::Parser::WithExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 32)
  def _reduce_16(val, _values, result)
     result = Bamboo::Engine::Parser::StatementList.new; result.add_statement(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 33)
  def _reduce_17(val, _values, result)
     result = val[0]; result.add_statement(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 35)
  def _reduce_18(val, _values, result)
     result = Bamboo::Engine::Parser::DataSet.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 42)
  def _reduce_21(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 43)
  def _reduce_22(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 45)
  def _reduce_23(val, _values, result)
     result = Bamboo::Engine::Parser::LetExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 48)
  def _reduce_24(val, _values, result)
        @context.set_ns(val[1].gsub(/^xmlns:/, ''), val[3])
  
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 51)
  def _reduce_25(val, _values, result)
     result = Bamboo::Engine::Parser::IfExpr.new(val[2], val[5], val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 52)
  def _reduce_26(val, _values, result)
     result = Bamboo::Engine::Parser::IfExpr.new(val[2], val[5], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 54)
  def _reduce_27(val, _values, result)
     result = Bamboo::Engine::Parser::ForExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 56)
  def _reduce_28(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 57)
  def _reduce_29(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 59)
  def _reduce_30(val, _values, result)
     result = Bamboo::Engine::Parser::ForVar.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 61)
  def _reduce_31(val, _values, result)
     result = Bamboo::Engine::Parser::SomeExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 62)
  def _reduce_32(val, _values, result)
     result = Bamboo::Engine::Parser::EveryExpr.new(val[1], val[3]) 
    result
  end
.,.,

# reduce 33 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 65)
  def _reduce_34(val, _values, result)
     result = Bamboo::Engine::Parser::OrExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 35 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 68)
  def _reduce_36(val, _values, result)
     result = Bamboo::Engine::Parser::AndExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 69)
  def _reduce_37(val, _values, result)
     result = Bamboo::Engine::Parser::ExceptExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 38 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 72)
  def _reduce_39(val, _values, result)
     result = Bamboo::Engine::Parser::EqExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 73)
  def _reduce_40(val, _values, result)
     result = Bamboo::Engine::Parser::NeqExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 75)
  def _reduce_41(val, _values, result)
     result = Bamboo::Engine::Parser::Tuple.new(val[1]) 
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 80)
  def _reduce_43(val, _values, result)
     result = Bamboo::Engine::Parser::LtExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 81)
  def _reduce_44(val, _values, result)
     result = Bamboo::Engine::Parser::LtExpr.new(val[2], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 82)
  def _reduce_45(val, _values, result)
     result = Bamboo::Engine::Parser::LteExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 83)
  def _reduce_46(val, _values, result)
     result = Bamboo::Engine::Parser::LteExpr.new(val[2], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 94)
  def _reduce_47(val, _values, result)
     result = Bamboo::Engine::Parser::RangeExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 95)
  def _reduce_48(val, _values, result)
     result = Bamboo::Engine::Parser::RangeExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 49 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 98)
  def _reduce_50(val, _values, result)
     result = Bamboo::Engine::Parser::AddExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 99)
  def _reduce_51(val, _values, result)
     result = Bamboo::Engine::Parser::SubExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 52 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 102)
  def _reduce_53(val, _values, result)
     result = Bamboo::Engine::Parser::MpyExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 103)
  def _reduce_54(val, _values, result)
     result = Bamboo::Engine::Parser::DivExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 104)
  def _reduce_55(val, _values, result)
     result = Bamboo::Engine::Parser::ModExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 107)
  def _reduce_57(val, _values, result)
     result = Bamboo::Engine::Parser::NegExpr.new(val[1]) 
    result
  end
.,.,

# reduce 58 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 110)
  def _reduce_59(val, _values, result)
     result = Bamboo::Engine::Parser::UnionExpr.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 112)
  def _reduce_60(val, _values, result)
     result = [ val[0], val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 113)
  def _reduce_61(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 115)
  def _reduce_62(val, _values, result)
     result = Bamboo::Engine::Parser::PathExpr.new(nil, [], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 116)
  def _reduce_63(val, _values, result)
     result = ((val[1].nil? || val[1].empty?) && (val[2].nil? || val[2].empty?)) ? val[0] : Bamboo::Engine::Parser::PathExpr.new(val[0], val[1], val[2]) 
    result
  end
.,.,

# reduce 64 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 119)
  def _reduce_65(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 120)
  def _reduce_66(val, _values, result)
     result = [ Bamboo::Engine::Parser::AxisDescendentOrSelf.new ] + val[1] 
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 128)
  def _reduce_69(val, _values, result)
     result = Bamboo::Engine::Parser::RootContext.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 129)
  def _reduce_70(val, _values, result)
     result = Bamboo::Engine::Parser::PathExpr.new(Bamboo::Engine::Parser::RootContext.new, [], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 130)
  def _reduce_71(val, _values, result)
     result = [ Bamboo::Engine::Parser::RootContext.new, Bamboo::Engine::Parser::AxisDescendentOrSelf.new(val[1][0]) ] + val[1][1..val[1].size-1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 131)
  def _reduce_72(val, _values, result)
     result = [ Bamboo::Engine::Parser::RootContext.new(val[0]) ] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 132)
  def _reduce_73(val, _values, result)
     result = [ Bamboo::Engine::Parser::RootContext.new(val[0]), Bamboo::Engine::Parser::AxisDescendentOrSelf.new(val[2][0]) ] + val[2][1..val[2].size-1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 134)
  def _reduce_74(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 135)
  def _reduce_75(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 136)
  def _reduce_76(val, _values, result)
     result = val[0] + [ Bamboo::Engine::Parser::AxisDescendentOrSelf.new(val[2]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 138)
  def _reduce_77(val, _values, result)
     result = val[1].nil? || val[1].empty? ? val[0] : Bamboo::Engine::Parser::Predicates.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 139)
  def _reduce_78(val, _values, result)
     result = Bamboo::Engine::Parser::CurrentContext.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 140)
  def _reduce_79(val, _values, result)
     result = Bamboo::Engine::Parser::AxisParent.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 146)
  def _reduce_80(val, _values, result)
     result = Bamboo::Engine::Parser::AxisChild.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 147)
  def _reduce_81(val, _values, result)
     result = Bamboo::Engine::Parser::Axis.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 148)
  def _reduce_82(val, _values, result)
     result = Bamboo::Engine::Parser::AxisAttribute.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 150)
  def _reduce_83(val, _values, result)
     result = Bamboo::Engine::Parser::Axis.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 152)
  def _reduce_84(val, _values, result)
     result = [ ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 153)
  def _reduce_85(val, _values, result)
     result = val[0] + [ val[1] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 155)
  def _reduce_86(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 156)
  def _reduce_87(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 163)
  def _reduce_88(val, _values, result)
     result = Bamboo::Engine::Parser::Var.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 164)
  def _reduce_89(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 90 omitted

# reduce 91 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 167)
  def _reduce_92(val, _values, result)
     result = Bamboo::Engine::Parser::Literal.new(val[0], [ Bamboo::Engine::NS::FAB, 'string' ]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 168)
  def _reduce_93(val, _values, result)
     result = Bamboo::Engine::Parser::Literal.new(val[0] =~ /\./ ? val[0].to_d.to_r : val[0].to_i.to_r, [ Bamboo::Engine::NS::FAB, 'numeric' ]) 
    result
  end
.,.,

# reduce 94 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 170)
  def _reduce_95(val, _values, result)
     val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 172)
  def _reduce_96(val, _values, result)
            result = Bamboo::Engine::Parser::Function.new(@context, val[0], val[1]) 
#          when 'any' : Bamboo::Engine::Parser::AnyExpr.new(@context, val[1])
#          when 'all' : Bamboo::Engine::Parser::AllExpr.new(@context, val[1])
#          when 'one' : Bamboo::Engine::Parser::OneExpr.new(@context, val[1])
#          when 'none': Bamboo::Engine::Parser::NoneExpr.new(@context, val[1])
#          else Bamboo::Engine::Parser::Function.new(@context, val[0], val[1]) 
#        end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 181)
  def _reduce_97(val, _values, result)
     result = Bamboo::Engine::Parser::List.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 184)
  def _reduce_98(val, _values, result)
     result = [ ] 
    result
  end
.,.,

# reduce 99 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 187)
  def _reduce_100(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 188)
  def _reduce_101(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

# reduce 102 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 191)
  def _reduce_103(val, _values, result)
     result = val[0].to_s 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 192)
  def _reduce_104(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 105 omitted

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
    end   # module Engine
  end   # module Bamboo
