#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Utukku
  module Engine
    class Parser < Racc::Parser

module_eval(<<'...end engine-parser.racc/module_eval...', 'engine-parser.racc', 211)
  # == Utukku::Engine::Parser
  #
  # <tt>Utukku::Engine::Parser</tt> provides a parser for Utukku::Engine::Parser operating on a DOM-like data model provided by
  # Utukku::Engine::Memory::Context and Utukku::Engine::Memory::Node.
  #
  # The expression language is based on XQuery and XPath.
  #

  require 'utukku/engine'
  require 'rational'
  require 'bigdecimal'
  require 'bigdecimal/util'

  # Within the context of a Utukku::Engine::Memory::Context object, this will
  # parse the given string and return an object that can be run to return
  # an array if Utukku::Engine::Memory::Node objects.
  #
  # Example:
  #
  #   parser  = Utukku::Engine::Parser.new
  #   context = Utukku::Engine::Memory::Context.new
  #   expr    = parser.parse('//foo', context)
  #   foos    = expr.run(context)
  #
  # Results in 'foos' being an array of all of the nodes in the
  # context that are named 'foo' regardless of their depth in the
  # node tree.
  def parse(text, context)
    @source = text
    @curpos = 0
    @context = context #.merge
    @line = 0
    @col = 0

    @yydebug = true

    @last_token = nil

    do_parse
  end

  # Used internally by the parser to raise a Utukku::Engine::ParserError
  # when the parse fails.
  def on_error(*args)
    raise Utukku::Engine::ParserError.new("unable to parse '#{args[1]}' near line #{@line + 1}, column #{@col}")
  end


  @@regex = {
    :simple_tokens => %r{\.\.|::|!=|>=|<=|\/\/|\/>|:=|\(\{|\}\)|\.|@|[*]|\(|\)|\[|\]|\{|\}|\/|\||\+|-|=|>|<|&|,|;|#|:},
    :ncname => %r{(?:[a-zA-Z_][-a-zA-Z0-9_.]*)},
    :event_type => %r{(?:processing-instruction|comment|text|node)},
    :axis_name => %r{(?:attribute|child|child-or-self|descendant|descendant-or-self|method|self)},
    :namespace_name => %r{(?:context|global|local|session|universal)},
    :number => %r{((?:-?[0-9_]+(?:\.[0-9_]+)?|\.[0-9_]+)|(?:-?[0-9_]+/[0-9_]+))},
    :literal => %r{((?:"(?:[^\\"]*(?:\\.[^\\"]*)*)")|(?:'(?:[^\\']*(?:\\.[^\\']*)*)'))},
  }

  @@regex[:axis] = %r{(#{@@regex[:ncname]})\s*(?=::)}
  @@regex[:name_colon_star] = %r{(#{@@regex[:ncname]}:\*)}
  @@regex[:qname] = %r{((?:#{@@regex[:ncname]}:)?#{@@regex[:ncname]})}
  @@regex[:xmlns] = %r{((?:xmlns:)#{@@regex[:ncname]})}
  @@regex[:dollar_qname] = %r{\$#{@@regex[:qname]}}
  @@regex[:dollar_int] = %r{\$([0-9]+)}
  @@regex[:function_name] = %r{#{@@regex[:qname]}\??\*?\s*(?=\([^:])}

  @@ops = {
    '..' => :DOT_DOT,
    '::' => :COLON_COLON,
    '!=' => :NEQ,
    '>=' => :GTE,
    '<=' => :LTE,
    '//' => :SLASH_SLASH,
    '/>' => :SLASH_GT,
    ':=' => :COLON_EQUAL,
    '({' => :LP_LC,
    '})' => :RC_RP,
    ':'  => :COLON,
    '.'  => :DOT,
    '@'  => :AT,
    '*'  => :STAR,
    '('  => :LP,
    ')'  => :RP,
    '['  => :LB,
    ']'  => :RB,
    '{'  => :LC,
    '}'  => :RC,
    '/'  => :SLASH,
    '|'  => :PIPE,
    '+'  => :PLUS,
    '-'  => :MINUS,
    '='  => :EQ,
    '>'  => :GT,
    '<'  => :LT,
    '&'  => :AMP,
    ','  => :COMMA,
    ';'  => :SEMI,
    '#'  => :HASH,
  }

  @@preceding_tokens = { }
  [%{
    @ :: ( 
    and or mod div 
    * 
    / // | + - = != < <= > >=
    == & && ||
  }.split(/\s*/), '[', ',', '$' ].each { |t| @@preceding_tokens[t] = true }

  @@regex[:general] = Regexp.compile(%{^(?:#{@@regex[:xmlns]}|#{@@regex[:function_name]}|#{@@regex[:axis]}|#{@@regex[:name_colon_star]}|#{@@regex[:qname]}|#{@@regex[:literal]}|#{@@regex[:number]}|#{@@regex[:dollar_qname]}|#{@@regex[:dollar_int]}|(#{@@regex[:simple_tokens]}))})

  def next_token  
    @token = nil
    white_space = 0
    new_line = 0
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end

    # skip comments delimited by (:  :)
    # comments can be nested
    # these are XPath 2.0 comments
    #
    if @curpos < @source.length && @source[@curpos..@curpos+1] == '(:'
      comment_depth = 1
      @curpos = @curpos + 2
      @col = @col + 2
      while comment_depth > 0 && @curpos < @source.length
        if @source[@curpos..@curpos+1] == '(:'
          comment_depth = comment_depth + 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        if @source[@curpos..@curpos+1] == ':)'
          comment_depth = comment_depth - 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        @curpos = @curpos + 1
        @col = @col + 1
      end
      white_space = white_space + 1
    end

    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end
        
    if @curpos >= @source.length
      @last_token = nil
      return [ false, false ]
    end

    #if new_line > 0 || white_space > 0
    #  @token = [ :SP, '' ]
    #end

    if @token.nil? && @last_token && ! @@preceding_tokens[@last_token[1]]
      if @source[@curpos..@curpos] == '*'
        @token = [ :STAR, '*' ]
      else
        if @source[@curpos..@source.length-1] =~ /^(#{@@regex[:ncname]})/
          ncname = $1
          case ncname
            when 'for'
              @token = [ :FOR, 'for' ]
            when 'return'
              @token = [ :RETURN, 'return' ]
            when 'in'
              @token = [ :IN, 'in' ]
            when 'let'
              @token = [ :LET, 'let' ]
            when 'except'
              @token = [ :EXCEPT, 'except' ]
            when 'every'
              @token = [ :EVERY, 'every' ]
            when 'some'
              @token = [ :SOME, 'some' ]
            when 'satisfies'
              @token = [ :SATISFIES, 'satisfies' ]
            when 'if'
              @token = [ :IF, 'if' ]
            when 'then'
              @token = [ :THEN, 'then' ]
            when 'else'
              @token = [ :ELSE, 'else' ]
            when 'to'
              @token = [ :TO, 'to' ]
            when 'and'
              @token = [ :AND, 'and' ]
            when 'or'
              @token = [ :OR, 'or' ]
            when 'mod'
              @token = [ :MOD, 'mod' ]
            when 'div'
              @token = [ :DIV, 'div' ]
            when 'err'
              @token = [ :ERR, 'err' ]
            #when '*doh*':
            #  # do nothing
            #  @token = nil
            else
              @token = nil
          end
        end
      end
    end
 
    if @token.nil? && @source[@curpos..@curpos+1] == '..'
      @token = [ :DOT_DOT, '..' ]
    end

    if @token.nil?
      if @curpos >= @source.length
        @token = [false, false]
        return @token
      end

      res = @@regex[:general].match(@source[@curpos..@source.length-1])
      #@source[@curpos..@source.length-1] =~ @@regex[:general]
      #res = [ nil, $1, $2, $3, $4, $5, $6, $7, $8 ]
      if res.nil?
        raise "Failed to parse '#{@source}' at #{@curpos}': #{@source[@curpos..@source.length-1]}"
      else
        if !res[1].nil?
          @token = [ :XMLNS_COLON_NCNAME, res[1] ]
        elsif !res[2].nil?
          if res[2] == 'if'
            @token = [ :IF, 'if' ]
          else
            if @source[@curpos+res[2].length .. @curpos+res[2].length + 1] =~ /^(\??\*?)/
              @token = [ :FUNCTION_NAME, res[2]+$1 ]
            else
              @token = [ :FUNCTION_NAME, res[2] ]
            end
          end
        elsif !res[3].nil?
          @token = [ res[3] == 'method' ? :AXIS_METHOD : :AXIS_NAME, res[3] ]
        elsif !res[4].nil?
          @token = [ :NAME_COLON_STAR, res[4] ]
        elsif !res[5].nil?
          qname = res[5]
          case qname
            when 'for'
              @token = [ :FOR, 'for' ]
            when 'return'
              @token = [ :RETURN, 'return' ]
            when 'in'
              @token = [ :IN, 'in' ]
            when 'let'
              @token = [ :LET, 'let' ]
            when 'except'
              @token = [ :EXCEPT, 'except' ]
            when 'every'
              @token = [ :EVERY, 'every' ]
            when 'some'
              @token = [ :SOME, 'some' ]   
            when 'satisfies'
              @token = [ :SATISFIES, 'satisfies' ]
            when 'if'
              @token = [ :IF, 'if' ]
            when 'then'
              @token = [ :THEN, 'then' ]
            when 'else'
              @token = [ :ELSE, 'else' ]
            when 'with'
              @token = [ :WITH, 'with' ]
            when 'err'
              @token = [ :ERR, 'err' ]
            else
              @token = [ :QNAME, qname ]
          end
        elsif !res[6].nil?
          s = res[6]
          @curpos = @curpos + s.length
          @col = @col + s.length
          s = s[1..s.length-2]
          s.gsub!(/\\n/, "\n")
          s.gsub!(/\\'/, "'")
          s.gsub!(/\\"/, '"')
          @line += s.split(/\n/).count
          @curpos = @curpos - s.length
          @col = @col - s.length
          @token = [ :LITERAL, s ]
        elsif !res[7].nil?
          n = res[7].gsub(/_/,'')
          if n =~ /(.*)\/(.*)/
            n = Rational.new($1, $2)
          end
          @token = [ :NUMBER, res[7] ]
        elsif !res[8].nil?
          @curpos = @curpos + 1
          @col = @col + 1
          @token = [ :DOLLAR_QNAME, res[8] ]
        elsif !res[9].nil?
          @curpos = @curpos + 1
          @col = @col + 1
          @token = [ :DOLLAR_QNAME, res[9] ]
        elsif !res[10].nil?
          @token = [ @@ops[res[10]] || res[10], res[10] ]
        else
          raise "Failed to parse '#{@source}' at #{@curpos}: #{@source[@curpos..@source.length-1]}"
        end
      end
    end

    if !@token[1].nil?
      @curpos = @curpos + @token[1].length
      @col = @col + @token[1].length
    end
    @last_token = @token
    return @token
  end
...end engine-parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    82,    83,    39,    42,   123,    52,     6,     9,    21,   149,
   189,    29,    75,    76,    47,   136,    55,    82,    83,    22,
    58,   111,    28,   136,    36,    80,     1,   134,     4,   113,
   166,    17,    21,   190,   117,   137,    44,    49,    53,     3,
    10,    13,   188,    22,    26,    31,   136,    41,   118,   120,
     1,    39,    42,   115,    52,     6,     9,   150,    21,   151,
    29,   163,    72,    47,    73,    55,    82,    83,    96,    22,
    58,    28,   152,    36,    82,    83,     1,     4,   198,    80,
    17,    21,    69,    70,   124,    44,    49,    53,     3,    10,
    13,    90,    22,    26,    31,    86,    41,   -20,    42,     1,
    52,     6,     9,    21,    69,    70,    29,    82,    83,    47,
   184,    55,    82,    83,    22,    58,    96,    28,   191,    36,
   182,     1,   174,     4,    66,    67,    17,    21,   122,   -19,
   180,    44,    49,    53,     3,    10,    13,    85,    22,    26,
    31,   179,    41,   123,    42,     1,    52,    80,     9,   104,
   105,   130,   -19,   106,   107,   108,   109,   100,   101,   102,
   103,    82,    83,    28,   135,    36,    87,    88,    89,     4,
    69,    70,    17,    21,    87,    88,    89,    44,    49,    53,
     3,    10,    13,    80,    22,    26,    31,    21,    41,   146,
    42,     1,    52,   117,     9,    68,   104,   105,    22,    58,
   106,   107,   108,   109,   147,     1,   102,   103,    61,    28,
   148,    36,    87,    88,    89,     4,    82,    83,    17,    21,
    82,    83,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,   nil,
     9,   104,   105,    69,    70,   106,   107,   108,   109,   100,
   101,   102,   103,    69,    70,    28,   nil,    36,    82,    83,
   nil,     4,    82,    83,    17,    21,    82,    83,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,     6,     9,    82,    83,   nil,
    29,    82,    83,    47,   nil,    55,   100,   101,   102,   103,
   nil,    28,   nil,    36,    82,    83,   nil,     4,    82,    83,
    17,    21,    82,    83,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,   nil,     9,    69,    70,    69,    70,    92,    93,   102,
   103,   102,   103,    66,    67,   102,   103,    28,   nil,    36,
   102,   103,   nil,     4,   102,   103,    17,    21,   102,   103,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,   nil,     9,   102,
   103,   102,   103,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,   nil,    41,   nil,
    42,     1,    52,   nil,     9,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,    17,    21,
   nil,   nil,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,     6,
     9,   nil,   nil,   nil,    29,   nil,   nil,    47,   nil,    55,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,
   nil,     4,   nil,   nil,    17,    21,   nil,   nil,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,
    17,    21,   nil,   nil,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,     6,     9,   nil,   nil,   nil,    29,   nil,   nil,    47,
   nil,    55,   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,
   nil,   nil,   nil,     4,   nil,   nil,    17,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,   nil,     9,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,    42,     4,
    52,   nil,     9,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,    28,    41,    36,
   nil,     1,   nil,     4,   nil,   nil,    17,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,   nil,     9,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,   nil,    41,   nil,
    42,     1,    52,   nil,     9,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,    17,    21,
   nil,   nil,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,   nil,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,
   nil,     4,   nil,   nil,    17,    21,   nil,   nil,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,     6,     9,   nil,   nil,   nil,
    29,   nil,   nil,    47,   nil,    55,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,
    17,    21,   nil,   nil,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,     6,     9,   nil,   nil,   nil,    29,   nil,   nil,    47,
   nil,    55,   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,
   nil,   nil,   nil,     4,   nil,   nil,    17,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,     6,     9,   nil,
   nil,   nil,    29,   nil,   nil,    47,   nil,    55,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,   nil,    41,   nil,
    42,     1,    52,     6,     9,   nil,   nil,   nil,    29,   nil,
   nil,    47,   nil,    55,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,    17,    21,
   nil,   nil,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,     6,
     9,   nil,   nil,   nil,    29,   nil,   nil,    47,   nil,    55,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,
   nil,     4,   nil,   nil,    17,    21,   nil,   nil,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,
    17,    21,   nil,   nil,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,   nil,     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,
   nil,   nil,   nil,     4,   nil,   nil,   nil,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,     6,     9,   nil,
   nil,   nil,    29,   nil,   nil,    47,   nil,    55,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,   nil,    41,   nil,
    42,     1,    52,   nil,     9,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,    17,    21,
   nil,   nil,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,   nil,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,
   nil,     4,   nil,   nil,    17,    21,   nil,   nil,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,     6,     9,   nil,   nil,   nil,
    29,   nil,   nil,    47,   nil,    55,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,
    17,    21,   nil,   nil,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,     6,     9,   nil,   nil,   nil,    29,   nil,   nil,    47,
   nil,    55,   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,
   nil,   nil,   nil,     4,   nil,   nil,    17,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,     6,     9,   nil,
   nil,   nil,    29,   nil,   nil,    47,   nil,    55,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,   nil,    41,   nil,
    42,     1,    52,   nil,     9,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,    17,    21,
   nil,   nil,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,   nil,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,
   nil,     4,   nil,   nil,    17,    21,   nil,   nil,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,
    17,    21,   nil,   nil,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,   nil,     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,
   nil,   nil,   nil,     4,   nil,   nil,   nil,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,     6,     9,   nil,
   nil,   nil,    29,   nil,   nil,    47,   nil,    55,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,   nil,    22,    26,    31,   nil,    41,   nil,
    42,     1,    52,     6,     9,   nil,   nil,   nil,    29,   nil,
   nil,    47,   nil,    55,   nil,   nil,   nil,   nil,   nil,    28,
   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,    17,    21,
   nil,   nil,   nil,    44,    49,    53,     3,    10,    13,   nil,
    22,    26,    31,   nil,    41,   nil,    42,     1,    52,     6,
     9,   nil,   nil,   nil,    29,   nil,   nil,    47,   nil,    55,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,
   nil,     4,   nil,   nil,    17,    21,   nil,   nil,   nil,    44,
    49,    53,     3,    10,    13,   nil,    22,    26,    31,   nil,
    41,   nil,    42,     1,    52,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    28,   nil,    36,   nil,   nil,   nil,     4,   nil,   nil,
   nil,    21,   nil,   nil,   nil,    44,    49,    53,     3,    10,
    13,   nil,    22,    26,    31,   nil,    41,   nil,    42,     1,
    52,     6,     9,   nil,   nil,   nil,    29,   nil,   nil,    47,
   nil,    55,   nil,   nil,   nil,   nil,   nil,    28,   nil,    36,
   nil,   nil,   nil,     4,   nil,   nil,    17,    21,   nil,   nil,
   nil,    44,    49,    53,     3,    10,    13,   nil,    22,    26,
    31,   nil,    41,   nil,    42,     1,    52,   nil,     9,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,    36,   nil,   nil,   nil,     4,
   nil,   nil,    17,    21,   nil,   nil,   nil,    44,    49,    53,
     3,    10,    13,     4,    22,    26,    31,    21,    41,   nil,
   nil,     1,   nil,    53,     3,    10,    13,     4,    22,    58,
   nil,    21,   nil,   nil,   nil,     1,   nil,    53,     3,    10,
    13,     4,    22,    58,   nil,    21,   nil,   nil,   nil,     1,
   nil,    53,     3,    10,    13,     4,    22,    58,   nil,    21,
   nil,   nil,   nil,     1,   nil,    53,     3,    10,    13,     4,
    22,    58,   nil,    21,   nil,   nil,   nil,     1,   nil,    53,
     3,    10,    13,     4,    22,    58,   nil,    21,   nil,   nil,
   nil,     1,   nil,    53,     3,    10,    13,     4,    22,    58,
   nil,    21,   nil,   nil,   nil,     1,   nil,    53,     3,    10,
    13,     4,    22,    58,   nil,    21,   nil,   nil,   nil,     1,
   nil,    53,     3,    10,    13,   nil,    22,    58,   nil,   nil,
   nil,   nil,   nil,     1 ]

racc_action_check = [
    57,    57,    73,    73,    77,    73,    73,    73,    27,    94,
   170,    73,    27,    27,    73,   114,    73,   167,   167,    27,
    27,    48,    73,    81,    73,    47,    27,    77,    73,    50,
   114,    73,    73,   170,    60,    81,    73,    73,    73,    73,
    73,    73,   167,    73,    73,    73,   110,    73,    60,    60,
    73,     0,     0,    57,     0,     0,     0,    94,    10,    97,
     0,   110,    20,     0,    20,     0,   197,   197,    41,    10,
    10,     0,    97,     0,    64,    64,    10,     0,   197,    55,
     0,     0,   112,   112,    64,     0,     0,     0,     0,     0,
     0,    36,     0,     0,     0,    33,     0,   171,     9,     0,
     9,     9,     9,    99,    98,    98,     9,   199,   199,     9,
   151,     9,   121,   121,    99,    99,   149,     9,   174,     9,
   148,    99,   121,     9,    11,    11,     9,     9,    62,   169,
   141,     9,     9,     9,     9,     9,     9,    31,     9,     9,
     9,   139,     9,    63,   108,     9,   108,   136,   108,   169,
   169,    72,   169,   169,   169,   169,   169,   169,   169,   169,
   169,   193,   193,   108,    80,   108,   156,   156,   156,   108,
    16,    16,   108,   108,    34,    34,    34,   108,   108,   108,
   108,   108,   108,    29,   108,   108,   108,     3,   108,    90,
   107,   108,   107,    91,   107,    13,   126,   126,     3,     3,
   126,   126,   126,   126,    92,     3,   126,   126,     6,   107,
    93,   107,   155,   155,   155,   107,   187,   187,   107,   107,
    78,    78,   nil,   107,   107,   107,   107,   107,   107,   nil,
   107,   107,   107,   nil,   107,   nil,   106,   107,   106,   nil,
   106,    46,    46,   132,   132,    46,    46,    46,    46,    46,
    46,    46,    46,   133,   133,   106,   nil,   106,   186,   186,
   nil,   106,   185,   185,   106,   106,   181,   181,   nil,   106,
   106,   106,   106,   106,   106,   nil,   106,   106,   106,   nil,
   106,   nil,   191,   106,   191,   191,   191,   138,   138,   nil,
   191,    30,    30,   191,   nil,   191,   195,   195,   195,   195,
   nil,   191,   nil,   191,   178,   178,   nil,   191,   176,   176,
   191,   191,   175,   175,   nil,   191,   191,   191,   191,   191,
   191,   nil,   191,   191,   191,   nil,   191,   nil,    17,   191,
    17,   nil,    17,   173,   173,   172,   172,    39,    39,   153,
   153,   154,   154,   164,   164,   162,   162,    17,   nil,    17,
   157,   157,   nil,    17,   158,   158,    17,    17,   159,   159,
   nil,    17,    17,    17,    17,    17,    17,   nil,    17,    17,
    17,   nil,    17,   nil,   105,    17,   105,   nil,   105,   161,
   161,   160,   160,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   105,   nil,   105,   nil,   nil,   nil,   105,
   nil,   nil,   105,   105,   nil,   nil,   nil,   105,   105,   105,
   105,   105,   105,   nil,   105,   105,   105,   nil,   105,   nil,
   104,   105,   104,   nil,   104,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   104,
   nil,   104,   nil,   nil,   nil,   104,   nil,   nil,   104,   104,
   nil,   nil,   nil,   104,   104,   104,   104,   104,   104,   nil,
   104,   104,   104,   nil,   104,   nil,    28,   104,    28,    28,
    28,   nil,   nil,   nil,    28,   nil,   nil,    28,   nil,    28,
   nil,   nil,   nil,   nil,   nil,    28,   nil,    28,   nil,   nil,
   nil,    28,   nil,   nil,    28,    28,   nil,   nil,   nil,    28,
    28,    28,    28,    28,    28,   nil,    28,    28,    28,   nil,
    28,   nil,   189,    28,   189,   nil,   189,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   189,   nil,   189,   nil,   nil,   nil,   189,   nil,   nil,
   189,   189,   nil,   nil,   nil,   189,   189,   189,   189,   189,
   189,   nil,   189,   189,   189,   nil,   189,   nil,   180,   189,
   180,   180,   180,   nil,   nil,   nil,   180,   nil,   nil,   180,
   nil,   180,   nil,   nil,   nil,   nil,   nil,   180,   nil,   180,
   nil,   nil,   nil,   180,   nil,   nil,   180,   180,   nil,   nil,
   nil,   180,   180,   180,   180,   180,   180,   nil,   180,   180,
   180,   nil,   180,   nil,   179,   180,   179,   nil,   179,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   179,   nil,   179,   nil,   nil,   103,   179,
   103,   nil,   103,   179,   nil,   nil,   nil,   179,   179,   179,
   179,   179,   179,   nil,   179,   179,   179,   103,   179,   103,
   nil,   179,   nil,   103,   nil,   nil,   103,   103,   nil,   nil,
   nil,   103,   103,   103,   103,   103,   103,   nil,   103,   103,
   103,   nil,   103,   nil,   102,   103,   102,   nil,   102,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   102,   nil,   102,   nil,   nil,   nil,   102,
   nil,   nil,   102,   102,   nil,   nil,   nil,   102,   102,   102,
   102,   102,   102,   nil,   102,   102,   102,   nil,   102,   nil,
   101,   102,   101,   nil,   101,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   101,
   nil,   101,   nil,   nil,   nil,   101,   nil,   nil,   101,   101,
   nil,   nil,   nil,   101,   101,   101,   101,   101,   101,   nil,
   101,   101,   101,   nil,   101,   nil,   100,   101,   100,   nil,
   100,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   100,   nil,   100,   nil,   nil,
   nil,   100,   nil,   nil,   100,   100,   nil,   nil,   nil,   100,
   100,   100,   100,   100,   100,   nil,   100,   100,   100,   nil,
   100,   nil,   166,   100,   166,   166,   166,   nil,   nil,   nil,
   166,   nil,   nil,   166,   nil,   166,   nil,   nil,   nil,   nil,
   nil,   166,   nil,   166,   nil,   nil,   nil,   166,   nil,   nil,
   166,   166,   nil,   nil,   nil,   166,   166,   166,   166,   166,
   166,   nil,   166,   166,   166,   nil,   166,   nil,   198,   166,
   198,   198,   198,   nil,   nil,   nil,   198,   nil,   nil,   198,
   nil,   198,   nil,   nil,   nil,   nil,   nil,   198,   nil,   198,
   nil,   nil,   nil,   198,   nil,   nil,   198,   198,   nil,   nil,
   nil,   198,   198,   198,   198,   198,   198,   nil,   198,   198,
   198,   nil,   198,   nil,   117,   198,   117,   117,   117,   nil,
   nil,   nil,   117,   nil,   nil,   117,   nil,   117,   nil,   nil,
   nil,   nil,   nil,   117,   nil,   117,   nil,   nil,   nil,   117,
   nil,   nil,   117,   117,   nil,   nil,   nil,   117,   117,   117,
   117,   117,   117,   nil,   117,   117,   117,   nil,   117,   nil,
   163,   117,   163,   163,   163,   nil,   nil,   nil,   163,   nil,
   nil,   163,   nil,   163,   nil,   nil,   nil,   nil,   nil,   163,
   nil,   163,   nil,   nil,   nil,   163,   nil,   nil,   163,   163,
   nil,   nil,   nil,   163,   163,   163,   163,   163,   163,   nil,
   163,   163,   163,   nil,   163,   nil,   123,   163,   123,   123,
   123,   nil,   nil,   nil,   123,   nil,   nil,   123,   nil,   123,
   nil,   nil,   nil,   nil,   nil,   123,   nil,   123,   nil,   nil,
   nil,   123,   nil,   nil,   123,   123,   nil,   nil,   nil,   123,
   123,   123,   123,   123,   123,   nil,   123,   123,   123,   nil,
   123,   nil,    89,   123,    89,   nil,    89,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    89,   nil,    89,   nil,   nil,   nil,    89,   nil,   nil,
    89,    89,   nil,   nil,   nil,    89,    89,    89,    89,    89,
    89,   nil,    89,    89,    89,   nil,    89,   nil,   113,    89,
   113,   nil,   113,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   113,   nil,   113,
   nil,   nil,   nil,   113,   nil,   nil,   nil,   113,   nil,   nil,
   nil,   113,   113,   113,   113,   113,   113,   nil,   113,   113,
   113,   nil,   113,   nil,   152,   113,   152,   152,   152,   nil,
   nil,   nil,   152,   nil,   nil,   152,   nil,   152,   nil,   nil,
   nil,   nil,   nil,   152,   nil,   152,   nil,   nil,   nil,   152,
   nil,   nil,   152,   152,   nil,   nil,   nil,   152,   152,   152,
   152,   152,   152,   nil,   152,   152,   152,   nil,   152,   nil,
   109,   152,   109,   nil,   109,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   109,
   nil,   109,   nil,   nil,   nil,   109,   nil,   nil,   109,   109,
   nil,   nil,   nil,   109,   109,   109,   109,   109,   109,   nil,
   109,   109,   109,   nil,   109,   nil,    88,   109,    88,   nil,
    88,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    88,   nil,    88,   nil,   nil,
   nil,    88,   nil,   nil,    88,    88,   nil,   nil,   nil,    88,
    88,    88,    88,    88,    88,   nil,    88,    88,    88,   nil,
    88,   nil,    61,    88,    61,    61,    61,   nil,   nil,   nil,
    61,   nil,   nil,    61,   nil,    61,   nil,   nil,   nil,   nil,
   nil,    61,   nil,    61,   nil,   nil,   nil,    61,   nil,   nil,
    61,    61,   nil,   nil,   nil,    61,    61,    61,    61,    61,
    61,   nil,    61,    61,    61,   nil,    61,   nil,   147,    61,
   147,   147,   147,   nil,   nil,   nil,   147,   nil,   nil,   147,
   nil,   147,   nil,   nil,   nil,   nil,   nil,   147,   nil,   147,
   nil,   nil,   nil,   147,   nil,   nil,   147,   147,   nil,   nil,
   nil,   147,   147,   147,   147,   147,   147,   nil,   147,   147,
   147,   nil,   147,   nil,   137,   147,   137,   137,   137,   nil,
   nil,   nil,   137,   nil,   nil,   137,   nil,   137,   nil,   nil,
   nil,   nil,   nil,   137,   nil,   137,   nil,   nil,   nil,   137,
   nil,   nil,   137,   137,   nil,   nil,   nil,   137,   137,   137,
   137,   137,   137,   nil,   137,   137,   137,   nil,   137,   nil,
    87,   137,    87,   nil,    87,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    87,
   nil,    87,   nil,   nil,   nil,    87,   nil,   nil,    87,    87,
   nil,   nil,   nil,    87,    87,    87,    87,    87,    87,   nil,
    87,    87,    87,   nil,    87,   nil,    66,    87,    66,   nil,
    66,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    66,   nil,    66,   nil,   nil,
   nil,    66,   nil,   nil,    66,    66,   nil,   nil,   nil,    66,
    66,    66,    66,    66,    66,   nil,    66,    66,    66,   nil,
    66,   nil,    67,    66,    67,   nil,    67,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    67,   nil,    67,   nil,   nil,   nil,    67,   nil,   nil,
    67,    67,   nil,   nil,   nil,    67,    67,    67,    67,    67,
    67,   nil,    67,    67,    67,   nil,    67,   nil,    86,    67,
    86,   nil,    86,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    86,   nil,    86,
   nil,   nil,   nil,    86,   nil,   nil,   nil,    86,   nil,   nil,
   nil,    86,    86,    86,    86,    86,    86,   nil,    86,    86,
    86,   nil,    86,   nil,    85,    86,    85,    85,    85,   nil,
   nil,   nil,    85,   nil,   nil,    85,   nil,    85,   nil,   nil,
   nil,   nil,   nil,    85,   nil,    85,   nil,   nil,   nil,    85,
   nil,   nil,    85,    85,   nil,   nil,   nil,    85,    85,    85,
    85,    85,    85,   nil,    85,    85,    85,   nil,    85,   nil,
   135,    85,   135,   135,   135,   nil,   nil,   nil,   135,   nil,
   nil,   135,   nil,   135,   nil,   nil,   nil,   nil,   nil,   135,
   nil,   135,   nil,   nil,   nil,   135,   nil,   nil,   135,   135,
   nil,   nil,   nil,   135,   135,   135,   135,   135,   135,   nil,
   135,   135,   135,   nil,   135,   nil,     1,   135,     1,     1,
     1,   nil,   nil,   nil,     1,   nil,   nil,     1,   nil,     1,
   nil,   nil,   nil,   nil,   nil,     1,   nil,     1,   nil,   nil,
   nil,     1,   nil,   nil,     1,     1,   nil,   nil,   nil,     1,
     1,     1,     1,     1,     1,   nil,     1,     1,     1,   nil,
     1,   nil,    83,     1,    83,   nil,    83,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    83,   nil,    83,   nil,   nil,   nil,    83,   nil,   nil,
   nil,    83,   nil,   nil,   nil,    83,    83,    83,    83,    83,
    83,   nil,    83,    83,    83,   nil,    83,   nil,    82,    83,
    82,    82,    82,   nil,   nil,   nil,    82,   nil,   nil,    82,
   nil,    82,   nil,   nil,   nil,   nil,   nil,    82,   nil,    82,
   nil,   nil,   nil,    82,   nil,   nil,    82,    82,   nil,   nil,
   nil,    82,    82,    82,    82,    82,    82,   nil,    82,    82,
    82,   nil,    82,   nil,   111,    82,   111,   nil,   111,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   111,   nil,   111,   nil,   nil,   nil,   111,
   nil,   nil,   111,   111,   nil,   nil,   nil,   111,   111,   111,
   111,   111,   111,    49,   111,   111,   111,    49,   111,   nil,
   nil,   111,   nil,    49,    49,    49,    49,    70,    49,    49,
   nil,    70,   nil,   nil,   nil,    49,   nil,    70,    70,    70,
    70,    69,    70,    70,   nil,    69,   nil,   nil,   nil,    70,
   nil,    69,    69,    69,    69,   120,    69,    69,   nil,   120,
   nil,   nil,   nil,    69,   nil,   120,   120,   120,   120,    44,
   120,   120,   nil,    44,   nil,   nil,   nil,   120,   nil,    44,
    44,    44,    44,    75,    44,    44,   nil,    75,   nil,   nil,
   nil,    44,   nil,    75,    75,    75,    75,    76,    75,    75,
   nil,    76,   nil,   nil,   nil,    75,   nil,    76,    76,    76,
    76,   118,    76,    76,   nil,   118,   nil,   nil,   nil,    76,
   nil,   118,   118,   118,   118,   nil,   118,   118,   nil,   nil,
   nil,   nil,   nil,   118 ]

racc_action_pointer = [
    44,  1678,   nil,   150,   nil,   nil,   196,   nil,   nil,    90,
    21,   101,   nil,   148,   nil,   nil,   129,   320,   nil,   nil,
    62,   nil,   nil,   nil,   nil,   nil,   nil,   -29,   458,   175,
   288,   125,   nil,    55,   137,   nil,    43,   nil,   nil,   329,
   nil,    20,   nil,   nil,  1886,   nil,   216,    17,    -1,  1830,
   -11,   nil,   nil,   nil,   nil,    71,   nil,    -3,   nil,   nil,
     7,  1264,   115,   138,    71,   nil,  1448,  1494,   nil,  1858,
  1844,   nil,   151,    -5,   nil,  1900,  1914,    -1,   217,   nil,
   146,    18,  1770,  1724,   nil,  1586,  1540,  1402,  1218,  1034,
   138,   166,   198,   204,     4,   nil,   nil,    18,    63,    66,
   758,   712,   666,   620,   412,   366,   228,   182,   136,  1172,
    41,  1816,    41,  1080,    10,   nil,   nil,   896,  1928,   nil,
  1872,   109,   nil,   988,   nil,   nil,   171,   nil,   nil,   nil,
   nil,   nil,   202,   212,   nil,  1632,   139,  1356,   284,   136,
   nil,   124,   nil,   nil,   nil,   nil,   nil,  1310,   110,    68,
   nil,    62,  1126,   304,   306,   175,   129,   315,   319,   323,
   346,   344,   310,   942,   320,   nil,   804,    14,   nil,   124,
     5,    92,   294,   292,   104,   309,   305,   nil,   301,   596,
   550,   263,   nil,   nil,   nil,   259,   255,   213,   nil,   504,
   nil,   274,   nil,   158,   nil,   263,   nil,    63,   850,   104 ]

racc_action_default = [
    -3,  -114,   -93,  -114,   -79,   -85,  -114,   -10,   -94,  -106,
  -114,   -33,   -11,  -114,   -35,   -12,   -67,  -114,   -38,   -13,
  -114,  -113,  -110,   -95,   -68,    -1,   -97,  -114,  -114,  -114,
    -4,   -98,   -74,   -58,   -49,    -5,  -114,   -85,   -52,  -114,
    -6,  -114,   -91,   -80,   -69,   -56,   -42,  -114,    -7,  -114,
   -59,    -8,   -96,   -78,   -62,  -114,    -9,  -114,  -111,   -82,
   -64,  -114,  -114,  -107,  -108,   -83,  -114,  -114,   -84,  -114,
  -114,   -57,  -114,    -3,   -81,  -114,  -114,  -114,  -108,   -28,
  -114,  -114,  -114,  -114,  -100,  -106,  -114,  -114,  -114,  -114,
  -114,   -77,  -114,  -114,  -114,  -103,   -89,  -114,   -70,  -114,
  -114,  -114,  -114,  -114,  -114,  -114,  -114,  -114,  -114,  -114,
  -114,  -114,   -71,  -114,  -114,  -112,   -63,  -114,  -114,   -86,
  -114,  -114,  -101,  -114,   -92,   -36,   -42,   -37,   -75,   -76,
   200,    -2,   -72,   -73,   -41,  -114,  -114,  -114,   -14,   -15,
   -16,  -114,   -60,   -53,   -54,   -55,   -99,  -114,  -114,  -114,
  -102,  -114,  -114,   -47,   -48,   -50,   -51,   -39,   -40,   -43,
   -44,   -45,   -46,  -114,   -34,   -61,  -114,  -114,   -21,   -42,
  -114,    -8,   -65,   -66,  -114,  -109,   -30,   -29,   -27,  -114,
  -114,   -23,   -24,  -104,   -90,  -105,   -31,   -32,   -87,  -114,
   -88,  -114,   -17,   -18,   -22,   -19,   -20,   -26,  -114,   -25 ]

racc_goto_table = [
    57,   126,   126,    95,   141,    59,   140,   142,    64,    25,
    77,   171,    65,    60,   116,    71,    98,   168,   128,   129,
   164,   112,   155,   156,   125,   127,   177,    78,   170,    74,
   139,    84,    99,    81,   165,   153,   154,    99,    94,   157,
   158,   159,   160,   161,   162,    91,   126,   132,   133,    20,
   nil,   110,   169,   nil,   nil,   nil,   nil,    99,    99,   114,
   121,   nil,   nil,    99,    99,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   138,   131,   196,    78,   143,   144,   145,   nil,   194,
   172,   nil,   173,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   141,    74,   192,   nil,   nil,   nil,    99,   nil,    99,   nil,
   nil,   183,   nil,   nil,   nil,   nil,   167,   nil,   nil,   nil,
   nil,   nil,   175,   nil,   195,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   176,   nil,   178,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   181,   nil,   nil,   nil,
   nil,   185,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   186,   nil,   nil,   187,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   193,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   197,   nil,   nil,   nil,   nil,   nil,   nil,   199 ]

racc_goto_check = [
     3,    17,    17,    46,    15,    39,    14,    15,     3,     2,
    25,     7,    39,    32,    33,    27,    34,    16,    37,    37,
    21,    34,    26,    26,    22,    22,    20,     3,    18,    39,
    13,    42,    36,    19,    15,    17,    17,    36,    45,    17,
    17,    17,    17,    17,    17,    32,    17,    34,    34,     1,
   nil,    19,    17,   nil,   nil,   nil,   nil,    36,    36,    19,
     3,   nil,   nil,    36,    36,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     3,     2,     7,     3,    27,    27,    27,   nil,    16,
    34,   nil,    34,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    15,    39,    14,   nil,   nil,   nil,    36,   nil,    36,   nil,
   nil,    46,   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,
   nil,   nil,     3,   nil,    17,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     3,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    49,     9,    -1,   nil,   nil,   nil,  -106,   nil,   nil,
   nil,   nil,   nil,   -53,   -77,   -79,  -100,   -65,   -89,     4,
  -110,   -91,   -42,   nil,   nil,   -18,   -80,    -2,   nil,   nil,
   nil,   nil,     8,   -46,   -28,   nil,   -12,   -51,   nil,     2,
   nil,   nil,     0,   nil,   nil,    -3,   -38 ]

racc_goto_default = [
   nil,   nil,   nil,    30,    35,    40,    48,    51,    56,     7,
    12,    15,    19,   nil,   nil,    33,   nil,    46,   nil,   nil,
    79,    11,    14,    18,    23,    63,    34,    38,    45,    50,
    54,     5,   nil,   nil,    16,    24,    27,    32,    37,    43,
   119,    97,     2,     8,    62,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 58, :_reduce_1,
  3, 58, :_reduce_2,
  0, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_6,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  3, 69, :_reduce_14,
  3, 68, :_reduce_15,
  1, 70, :_reduce_16,
  3, 70, :_reduce_17,
  3, 71, :_reduce_18,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  1, 75, :_reduce_21,
  3, 75, :_reduce_22,
  4, 61, :_reduce_23,
  4, 62, :_reduce_24,
  8, 65, :_reduce_25,
  6, 65, :_reduce_26,
  4, 66, :_reduce_27,
  1, 76, :_reduce_28,
  3, 76, :_reduce_29,
  3, 77, :_reduce_30,
  4, 67, :_reduce_31,
  4, 67, :_reduce_32,
  1, 63, :_reduce_none,
  3, 63, :_reduce_34,
  1, 78, :_reduce_none,
  3, 78, :_reduce_36,
  3, 78, :_reduce_37,
  1, 79, :_reduce_none,
  3, 79, :_reduce_39,
  3, 79, :_reduce_40,
  3, 81, :_reduce_41,
  1, 80, :_reduce_none,
  3, 80, :_reduce_43,
  3, 80, :_reduce_44,
  3, 80, :_reduce_45,
  3, 80, :_reduce_46,
  3, 64, :_reduce_47,
  3, 64, :_reduce_48,
  1, 74, :_reduce_none,
  3, 74, :_reduce_50,
  3, 74, :_reduce_51,
  1, 83, :_reduce_none,
  3, 83, :_reduce_53,
  3, 83, :_reduce_54,
  3, 83, :_reduce_55,
  1, 84, :_reduce_none,
  2, 84, :_reduce_57,
  1, 85, :_reduce_none,
  1, 85, :_reduce_59,
  3, 86, :_reduce_60,
  3, 86, :_reduce_61,
  1, 72, :_reduce_62,
  3, 72, :_reduce_63,
  0, 90, :_reduce_none,
  2, 90, :_reduce_65,
  2, 90, :_reduce_66,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 92, :_reduce_69,
  2, 92, :_reduce_70,
  2, 92, :_reduce_71,
  3, 92, :_reduce_72,
  3, 92, :_reduce_73,
  1, 91, :_reduce_74,
  3, 91, :_reduce_75,
  3, 91, :_reduce_76,
  2, 94, :_reduce_77,
  1, 94, :_reduce_78,
  1, 94, :_reduce_79,
  1, 95, :_reduce_80,
  2, 95, :_reduce_81,
  2, 95, :_reduce_82,
  2, 95, :_reduce_83,
  2, 93, :_reduce_84,
  0, 89, :_reduce_85,
  2, 89, :_reduce_86,
  3, 97, :_reduce_87,
  3, 97, :_reduce_88,
  1, 98, :_reduce_89,
  3, 98, :_reduce_90,
  1, 88, :_reduce_91,
  3, 88, :_reduce_92,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_96,
  1, 88, :_reduce_97,
  1, 88, :_reduce_none,
  3, 88, :_reduce_99,
  2, 88, :_reduce_100,
  3, 99, :_reduce_101,
  3, 100, :_reduce_102,
  1, 102, :_reduce_103,
  3, 102, :_reduce_104,
  3, 103, :_reduce_105,
  0, 101, :_reduce_106,
  1, 101, :_reduce_none,
  1, 82, :_reduce_108,
  3, 82, :_reduce_109,
  1, 96, :_reduce_none,
  1, 96, :_reduce_111,
  3, 96, :_reduce_112,
  1, 96, :_reduce_none ]

racc_reduce_n = 114

racc_shift_n = 200

racc_token_table = {
  false => 0,
  :error => 1,
  :SEMI => 2,
  :ERR => 3,
  :WITH => 4,
  :COMMA => 5,
  :COLON_EQUAL => 6,
  :LET => 7,
  :DOLLAR_QNAME => 8,
  :XMLNS_COLON_NCNAME => 9,
  :LITERAL => 10,
  :IF => 11,
  :LP => 12,
  :RP => 13,
  :THEN => 14,
  :ELSE => 15,
  :FOR => 16,
  :RETURN => 17,
  :IN => 18,
  :SOME => 19,
  :SATISFIES => 20,
  :EVERY => 21,
  :OR => 22,
  :AND => 23,
  :EXCEPT => 24,
  :EQ => 25,
  :NEQ => 26,
  :LB => 27,
  :RB => 28,
  :LT => 29,
  :GT => 30,
  :LTE => 31,
  :GTE => 32,
  :DOT_DOT => 33,
  :TO => 34,
  :PLUS => 35,
  :MINUS => 36,
  :STAR => 37,
  :DIV => 38,
  :MOD => 39,
  :PIPE => 40,
  :SLASH => 41,
  :SLASH_SLASH => 42,
  :DOT => 43,
  :AT => 44,
  :HASH => 45,
  :AXIS_NAME => 46,
  :COLON_COLON => 47,
  :QNAME => 48,
  :NUMBER => 49,
  :FUNCTION_NAME => 50,
  :SLASH_GT => 51,
  :LP_LC => 52,
  :RC_RP => 53,
  :COLON => 54,
  :LC => 55,
  :RC => 56 }

racc_nt_base = 57

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SEMI",
  "ERR",
  "WITH",
  "COMMA",
  "COLON_EQUAL",
  "LET",
  "DOLLAR_QNAME",
  "XMLNS_COLON_NCNAME",
  "LITERAL",
  "IF",
  "LP",
  "RP",
  "THEN",
  "ELSE",
  "FOR",
  "RETURN",
  "IN",
  "SOME",
  "SATISFIES",
  "EVERY",
  "OR",
  "AND",
  "EXCEPT",
  "EQ",
  "NEQ",
  "LB",
  "RB",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "DOT_DOT",
  "TO",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "MOD",
  "PIPE",
  "SLASH",
  "SLASH_SLASH",
  "DOT",
  "AT",
  "HASH",
  "AXIS_NAME",
  "COLON_COLON",
  "QNAME",
  "NUMBER",
  "FUNCTION_NAME",
  "SLASH_GT",
  "LP_LC",
  "RC_RP",
  "COLON",
  "LC",
  "RC",
  "$start",
  "statements",
  "statement",
  "expr",
  "let_expr",
  "ns_expr",
  "or_expr",
  "range_expr",
  "if_expr",
  "for_expr",
  "quant_expr",
  "with_expr",
  "err_expr",
  "expr_set_list",
  "expr_set",
  "path_expr",
  "num_expr",
  "additive_expr",
  "num_list",
  "for_vars",
  "for_var",
  "and_expr",
  "equality_expr",
  "relational_expr",
  "tuple",
  "args",
  "multiplicative_expr",
  "unary_expr",
  "union_expr",
  "union_expr_x",
  "location_path",
  "primary_expr",
  "predicates",
  "segment",
  "relative_location_path",
  "absolute_location_path",
  "axis_name",
  "step",
  "axis",
  "node_test",
  "predicate",
  "const_path",
  "list",
  "bag",
  "opt_args",
  "bag_kv_pairs",
  "bag_kv_pair" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 12)
  def _reduce_1(val, _values, result)
     result = Utukku::Engine::Parser::StatementList.new; result.add_statement(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 13)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_statement(val[2]) 
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 18)
  def _reduce_6(val, _values, result)
     result = nil 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 28)
  def _reduce_14(val, _values, result)
     result = Utukku::Engine::Parser::ErrExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 30)
  def _reduce_15(val, _values, result)
     result = Utukku::Engine::Parser::WithExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 32)
  def _reduce_16(val, _values, result)
     result = Utukku::Engine::Parser::StatementList.new; result.add_statement(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 33)
  def _reduce_17(val, _values, result)
     result = val[0]; result.add_statement(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 35)
  def _reduce_18(val, _values, result)
     result = Utukku::Engine::Parser::DataSet.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 42)
  def _reduce_21(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 43)
  def _reduce_22(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 45)
  def _reduce_23(val, _values, result)
     result = Utukku::Engine::Parser::LetExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 48)
  def _reduce_24(val, _values, result)
        @context.set_ns(val[1].gsub(/^xmlns:/, ''), val[3])
  
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 51)
  def _reduce_25(val, _values, result)
     result = Utukku::Engine::Parser::IfExpr.new(val[2], val[5], val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 52)
  def _reduce_26(val, _values, result)
     result = Utukku::Engine::Parser::IfExpr.new(val[2], val[5], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 54)
  def _reduce_27(val, _values, result)
     result = Utukku::Engine::Parser::ForExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 56)
  def _reduce_28(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 57)
  def _reduce_29(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 59)
  def _reduce_30(val, _values, result)
     result = Utukku::Engine::Parser::ForVar.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 61)
  def _reduce_31(val, _values, result)
     result = Utukku::Engine::Parser::SomeExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 62)
  def _reduce_32(val, _values, result)
     result = Utukku::Engine::Parser::EveryExpr.new(val[1], val[3]) 
    result
  end
.,.,

# reduce 33 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 65)
  def _reduce_34(val, _values, result)
     result = Utukku::Engine::Parser::OrExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 35 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 68)
  def _reduce_36(val, _values, result)
     result = Utukku::Engine::Parser::AndExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 69)
  def _reduce_37(val, _values, result)
     result = Utukku::Engine::Parser::ExceptExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 38 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 72)
  def _reduce_39(val, _values, result)
     result = Utukku::Engine::Parser::EqExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 73)
  def _reduce_40(val, _values, result)
     result = Utukku::Engine::Parser::NeqExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 75)
  def _reduce_41(val, _values, result)
     result = Utukku::Engine::Parser::Tuple.new(val[1]) 
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 80)
  def _reduce_43(val, _values, result)
     result = Utukku::Engine::Parser::LtExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 81)
  def _reduce_44(val, _values, result)
     result = Utukku::Engine::Parser::LtExpr.new(val[2], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 82)
  def _reduce_45(val, _values, result)
     result = Utukku::Engine::Parser::LteExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 83)
  def _reduce_46(val, _values, result)
     result = Utukku::Engine::Parser::LteExpr.new(val[2], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 94)
  def _reduce_47(val, _values, result)
     result = Utukku::Engine::Parser::RangeExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 95)
  def _reduce_48(val, _values, result)
     result = Utukku::Engine::Parser::RangeExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 49 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 98)
  def _reduce_50(val, _values, result)
     result = Utukku::Engine::Parser::AddExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 99)
  def _reduce_51(val, _values, result)
     result = Utukku::Engine::Parser::SubExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 52 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 102)
  def _reduce_53(val, _values, result)
     result = Utukku::Engine::Parser::MpyExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 103)
  def _reduce_54(val, _values, result)
     result = Utukku::Engine::Parser::DivExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 104)
  def _reduce_55(val, _values, result)
     result = Utukku::Engine::Parser::ModExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 107)
  def _reduce_57(val, _values, result)
     result = Utukku::Engine::Parser::NegExpr.new(val[1]) 
    result
  end
.,.,

# reduce 58 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 110)
  def _reduce_59(val, _values, result)
     result = Utukku::Engine::Parser::UnionExpr.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 112)
  def _reduce_60(val, _values, result)
     result = [ val[0], val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 113)
  def _reduce_61(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 115)
  def _reduce_62(val, _values, result)
     result = Utukku::Engine::Parser::PathExpr.new(nil, [], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 116)
  def _reduce_63(val, _values, result)
     result = ((val[1].nil? || val[1].empty?) && (val[2].nil? || val[2].empty?)) ? val[0] : Utukku::Engine::Parser::PathExpr.new(val[0], val[1], val[2]) 
    result
  end
.,.,

# reduce 64 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 119)
  def _reduce_65(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 120)
  def _reduce_66(val, _values, result)
     result = [ Utukku::Engine::Parser::AxisDescendentOrSelf.new ] + val[1] 
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 128)
  def _reduce_69(val, _values, result)
     result = Utukku::Engine::Parser::RootContext.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 129)
  def _reduce_70(val, _values, result)
     result = Utukku::Engine::Parser::PathExpr.new(Utukku::Engine::Parser::RootContext.new, [], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 130)
  def _reduce_71(val, _values, result)
     result = [ Utukku::Engine::Parser::RootContext.new, Utukku::Engine::Parser::AxisDescendentOrSelf.new(val[1][0]) ] + val[1][1..val[1].size-1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 131)
  def _reduce_72(val, _values, result)
     result = [ Utukku::Engine::Parser::RootContext.new(val[0]) ] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 132)
  def _reduce_73(val, _values, result)
     result = [ Utukku::Engine::Parser::RootContext.new(val[0]), Utukku::Engine::Parser::AxisDescendentOrSelf.new(val[2][0]) ] + val[2][1..val[2].size-1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 134)
  def _reduce_74(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 135)
  def _reduce_75(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 136)
  def _reduce_76(val, _values, result)
     result = val[0] + [ Utukku::Engine::Parser::AxisDescendentOrSelf.new(val[2]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 138)
  def _reduce_77(val, _values, result)
     result = val[1].nil? || val[1].empty? ? val[0] : Utukku::Engine::Parser::Predicates.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 139)
  def _reduce_78(val, _values, result)
     result = Utukku::Engine::Parser::CurrentContext.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 140)
  def _reduce_79(val, _values, result)
     result = Utukku::Engine::Parser::AxisParent.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 146)
  def _reduce_80(val, _values, result)
     result = Utukku::Engine::Parser::AxisChild.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 147)
  def _reduce_81(val, _values, result)
     result = Utukku::Engine::Parser::Axis.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 148)
  def _reduce_82(val, _values, result)
     result = Utukku::Engine::Parser::AxisAttribute.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 149)
  def _reduce_83(val, _values, result)
     result = Utukku::Engine::Parser::AxisMethod.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 151)
  def _reduce_84(val, _values, result)
     result = Utukku::Engine::Parser::Axis.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 153)
  def _reduce_85(val, _values, result)
     result = [ ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 154)
  def _reduce_86(val, _values, result)
     result = val[0] + [ val[1] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 156)
  def _reduce_87(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 157)
  def _reduce_88(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 159)
  def _reduce_89(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 160)
  def _reduce_90(val, _values, result)
     result = val[0] + "/" + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 167)
  def _reduce_91(val, _values, result)
     result = Utukku::Engine::Parser::Var.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 168)
  def _reduce_92(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 172)
  def _reduce_96(val, _values, result)
     result = Utukku::Engine::Parser::Literal.new(val[0], [ Utukku::Engine::NS::FAB, 'string' ]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 173)
  def _reduce_97(val, _values, result)
     result = Utukku::Engine::Parser::Literal.new(val[0] =~ /\./ ? val[0].to_d.to_r : val[0].to_i.to_r, [ Utukku::Engine::NS::FAB, 'numeric' ]) 
    result
  end
.,.,

# reduce 98 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 175)
  def _reduce_99(val, _values, result)
     val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 177)
  def _reduce_100(val, _values, result)
            result = Utukku::Engine::Parser::Function.new(@context, val[0], val[1]) 
#          when 'any' : Utukku::Engine::Parser::AnyExpr.new(@context, val[1])
#          when 'all' : Utukku::Engine::Parser::AllExpr.new(@context, val[1])
#          when 'one' : Utukku::Engine::Parser::OneExpr.new(@context, val[1])
#          when 'none': Utukku::Engine::Parser::NoneExpr.new(@context, val[1])
#          else Utukku::Engine::Parser::Function.new(@context, val[0], val[1]) 
#        end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 186)
  def _reduce_101(val, _values, result)
     result = Utukku::Engine::Parser::List.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 188)
  def _reduce_102(val, _values, result)
     result = Utukku::Engine::Parser::Bag.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 190)
  def _reduce_103(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 191)
  def _reduce_104(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 193)
  def _reduce_105(val, _values, result)
     result = [ val[0], val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 196)
  def _reduce_106(val, _values, result)
     result = [ ] 
    result
  end
.,.,

# reduce 107 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 199)
  def _reduce_108(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 200)
  def _reduce_109(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

# reduce 110 omitted

module_eval(<<'.,.,', 'engine-parser.racc', 203)
  def _reduce_111(val, _values, result)
     result = val[0].to_s 
    result
  end
.,.,

module_eval(<<'.,.,', 'engine-parser.racc', 204)
  def _reduce_112(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 113 omitted

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
    end   # module Engine
  end   # module Utukku
