#! /usr/bin/perl -w

use lib './blib/lib';
use Utukku::Client;
use Utukku::Engine;

use POE (Filter::Stream);

my $client = Utukku::Client -> new(
  url => 'http://localhost:3000/demo'
);

$client -> setup;

POE::Session -> create(
  inline_states => {
    _start  => sub {
      $_[KERNEL] -> yield('send_doubling_request');
      #$_[KERNEL] -> yield('send_request');
    },
    send_request => sub {
      print STDERR "Sending an echo request\n";
      $client -> request('echo', { foo => 'bar' });
      print STDERR "echo request sent\n";
    },
    send_doubling_request => sub {
      print STDERR "Sending a doubling request\n";
      my $ns = "http://www.example.com/echo/1.0#";
      my $handler = Utukku::Engine::TagLibRegistry -> instance -> handler($ns);
      if( $handler ) {
        my $it = $handler -> function_to_iterator('double', [
          Utukku::Engine::ConstantRangeIterator -> new(
            begin => 1, end => 10
          )
        ] );

        $_ -> () for $it -> invert({
          next => sub { print STDERR "  returned [$_[0]]\n"; },
          done => sub { print STDERR "  we're done with the doubling\n"; },
        });
      }
      else {
        print STDERR "Waiting a bit...\n";
        $_[KERNEL] -> delay(send_doubling_request => 1);
      }
    },
  }
);

$client -> run;

